### ISSUE TITLE
Laravel 5.2 when editing get only create new form

### ISSUE THREAD

**Issue by htunlogic** [FrozenNode/Laravel-Administrator#1004]
Hi, 
I started implementing one app with FrozenNode couple of days ago, and I seem to have an issue that I cannot figure out what to do.

I can display my model results, but when I try to edit an item, I get only the Create New form and following console log error:

> Uncaught TypeError: Cannot read property 'length' of undefined
> p.extend.each @ jquery-1.8.2.min.js:2admin.prepareEditFields @ admin.js:1074

> admin.viewModel.setData @ admin.js:483

> $.ajax.success @ admin.js:445

> k @ jquery-1.8.2.min.js:2

> l.fireWith @ jquery-1.8.2.min.js:2

> y @ jquery-1.8.2.min.js:2

> d @ jquery-1.8.2.min.js:2

My config file for User model is this:

` return [

 	'title' => 'Users',

 	'single' => 'user',

 	'model' => 'Yap\User',

	/**
	 * The display columns
	 */
	'columns' => [
		'id' => [
			'title' => 'User ID',
			'type' => 'key'
		],
		'full_name' => [
			'title' => 'Name',
			'select' => "CONCAT((:table).firstname, ' ', (:table).lastname)",
		],
		'role' => [
			'title' => 'Role',
			'relationship' => 'role',
			'select' => '(:table).name',
		],
		'address' => [
			'title' => 'Address',
			'select' => "CONCAT((:table).country, ' ', (:table).zip, ' ', (:table).city, ' ', (:table).street)",
		],
		'email' => [
			'title' => 'Email'
		],
		'phone' => [
			'title' => 'Phone'
		],
		'ip' => [
			'title' => 'IP Address'
		],
	],

	/**
	 * The filter set
	 */
	'filters' => [
		'firstname' => [
			'title' => 'First Name',
		],
		'lastname' => [
			'title' => 'Last Name',
		],
		'action' => [
			'title' => 'Last active',
			'type' => 'datetime',
		],
		'role' => [
			'title' => 'Roles',
			'type' => 'relationship',
			'name_field' => 'name',
		],
	],

	/**
	 * The editable fields
	 */
	'edit_fields' => [
		'id' => [
			'type' => 'key'
		],
		'firstname' => [
			'title' => 'First Name',
			'type' => 'text'
		],
		'lastname' => [
			'title' => 'Last Name',
			'type' => 'text'
		],
		'role' => [
			'title' => 'Role',
			'type' => 'relationship',
			'name_field' => 'name',
		],
		'email' => [
			'title' => 'Email',
			'type' => 'text',
		],
		'phone' => [
			'title' => 'Phone',
			'type' => 'text',
		],
	],

];`

All of those fields do exist, and data displays correctly, I can add new record as well, but cannot edit or do anything with it. I have tried php artisan vendor:publish multiple times, but nothing has changed. Please help, this is starting do drive me mad. :(

Cheers,
Tibor.

**Comment by ssfinney** [comment]
Check the config with the role relationship removed, and you should see that the relationship with the role is the problem. Post your models so we can get a better look as to what's going on.
