### ISSUE TITLE
PHP 7.2.4 sizeof(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by Cqcsldl** [FrozenNode/Laravel-Administrator#1068]
PHP 7.2.4 will return error message

 sizeof(): Parameter must be an array or an object that implements Countable

**Comment by martondob** [comment]
@Cqcsldl 
Did you find a solution to this? I have the same problem.

**Comment by martondob** [comment]
Found the solution here:
[(https://laravel-china.org/topics/8872/when-configuring-configadministratorusersphp-to-access-httplarabbstestadminusers-there-are-the-following-errors-whats-the-mistake#reply43209)]
