### ISSUE TITLE
Using custom views

### ISSUE THREAD

**Issue by davemathews** [FrozenNode/Laravel-Administrator#144]
How best can I use custom views that overwrite the blade templates used by administrator?

**Comment by bryan-kramer** [comment]
A very simple approach to overriding the administrator views is the following:

a) in the administrator.php config file, add the line
`View::prependNamespace('administrator', '/mypath/to/views');`

b) define your views in `/mypath/to/views`, e.g. your own copies of one of
`index.php`
`layouts/default.blade.php`
`partials/footer.blade.php`
`partials/header.blade.php`
`partials/menu.blade.php`

Keep the directory structure the same as in the administrator source.

**Comment by stevenbouma** [comment]
Thanks @bryan-kramer, works for me

**Comment by thachp** [comment]
@bryan-kramer   After I added View::prependNamespace('administrator', base_path('resources/views')); I get the error Fatal error: Uncaught exception 'ReflectionException' with message 'Class log does not exist'.

Any thought?

**Comment by jacob1237** [comment]
@thachp, for Laravel 5.1 you don't have to use `prependNamespace()`. Just create the following directory in your app root: `resources/views/vendor/administrator/`

Then you can override default Laravel Administrator views. Just keep the same directory structure like in @bryan-kramer's answer
