### ISSUE TITLE
Override your jquery ui

### ISSUE THREAD

**Issue by davemathews** [FrozenNode/Laravel-Administrator#167]
How can I override your jquery ui, without hacking the filters.php file in the bundle?  Any way to update or override your jquery ui you are using?  or can I get you to update the core code's jquery ui to include the draggable ui available?

**Comment by dimti** [comment]
Hi. I read about View::composer and add custom assets. But i no understand, where placed that code 
View::composer{...}
app/routes.php - system not worked,
config/adminsitrator.php - system not worked.

Where is ideal place?
