### ISSUE TITLE
Plupload integration

### ISSUE THREAD

**Issue by RodrigoEspinosa** [FrozenNode/Laravel-Administrator#185]
I see the plupload library in the public folder of the administrator but I can't see how to make it work, it is already integrated?

Maybe is already in use with the simple upload but I want to make a multiple upload for images, is there a easy way to get that?

Thanks!

**Comment by PabloRozin** [comment]
The solution you propose is good, but it would be greater if there was a field type "multifile" that allow you to add multiple files (images or others) integrated with one-to-many or many-to-many relations. The admin is awesome, buy I think that this functionality is realy usefull and necessary.
