### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by joey102030** [FrozenNode/Laravel-Administrator#190]
Is there an easy way enable drag & drop re-ordering of items? If not this would be a useful feature

I've looked through the documentation and watched the tutorials, apologies if i've missed something obvious.

**Comment by frederickdubois** [comment]
Though we can achieve it with the custom actions buttons with a "move up / down" button, this would indeed be a feature useful in many scenarios!

**Comment by cmarfil** [comment]
>Though we can achieve it with the custom actions buttons with a "move up / down" button, this would indeed be a feature useful in many scenarios!

Yes! +1!
