### ISSUE TITLE
Class itemconfig does not exist

### ISSUE THREAD

**Issue by handijk** [FrozenNode/Laravel-Administrator#219]
I'm getting this error when running my app on the testing server, on my dev environment everything works as expected. but on the testing server whenever i call the /admin page it redirects me to the default admin page (as it should) where i get this error:

ReflectionException
Class itemconfig does not exist

This itemconfig class is called at line 14 in the file /administrator/src/viewComposers.php 

The app is working with the exact same code on both servers.

**Comment by Adiasz** [comment]
Thanks guys, this topic is still very needful :-)
