### ISSUE TITLE
Easier interface for adding data to pivot tables

### ISSUE THREAD

**Issue by Morgon** [FrozenNode/Laravel-Administrator#257]
This is loosely related to #144, but one thing that would be extremely helpful is being able to have an edit view that allows the ability to visually add to a pivot table.

For instance, say a User owns a (large) number of Books. I'd like to have a view that allows me to see the list of Books for a User's account. Optimally, we could re-use the same interface as viewing all of the Users or all of the Books:

[Books for Morgon]
Title 1 / Author 1 / Description 1
Title 2 / Author 2 / Description 2
..etc..

Editing a record would simply allow you to disassociate the record with the primary parent (User in this case).
Creating a new one may be a bit tricky, as it would essentially need to be a search of the secondary parent (Book) so that we could save the association.
Laravel does handle these pivot tables in their relationships, I'd imagine those could be leveraged in something like this.

Any chance of this becoming a reality?  My project has a large number of large relational associations; I'd love to keep everything within the Administrator ecosystem if possible! :)

**Comment by amanpatel** [comment]
I am working on a solution right now, is anyone interested in this? I can create pull request only if someone is still looking for a solution.

**Comment by timbroder** [comment]
@amanpatel I am. Were you able to solve?
