### ISSUE TITLE
mp3 mime & Upload Progree 

### ISSUE THREAD

**Issue by abbaspalash** [FrozenNode/Laravel-Administrator#331]
Hi, I tried to use File Upload for mp3 uploading, limiting file upload by

'mimes' => 'mp3',

doesn't work.

and Is there option to see upload progree?

**Comment by emocentmagar** [comment]
I can't add mp3 files with Laravel 4.2 with mimes=>'mp3'.

**Comment by emocentmagar** [comment]
I got it working by changin 'mimes' => 'mp3' to 'mimes' => 'mpga'.
