### ISSUE TITLE
There are problems with your administrator.php config: The model config path option must be a valid directory

### ISSUE THREAD

**Issue by yudhistiro** [FrozenNode/Laravel-Administrator#342]
InvalidArgumentException
There are problems with your administrator.php config: The model config path option must be a valid directory. The settings config path option must be a valid directory

Where is a valid directory from??
In vendor folder??? 

Can you help me???

**Comment by vintots** [comment]
thanks @hamczu , I also encounter this issue by creating "administrator" and "settings" dirs fixed my error 👍
