### ISSUE TITLE
Custom Pages not honoring custom_page_view_path?

### ISSUE THREAD

**Issue by Morgon** [FrozenNode/Laravel-Administrator#366]
After reviewing some of the recent code for the new Custom Views (thanks!), there's an option to describe a 'custom page view path', a directory within app/views that it looks for templates.

This could be my misunderstanding of how this works, but my thought was that it would turn something like '/admin/page/admin.test' into simply '/admin/page/test' by specifying 'admin' as the custom page view path.
Or more visually:

```
return array(
    // snip
    'custom_page_view_path' => '',

    'menu' => array(
        'My Pages' => array(
            array('Test' => 'page.admin.test')
        )
    )
)
```

..to..

```
return array(
    // snip
    'custom_page_view_path' => 'admin',

    'menu' => array(
        'My Pages' => array(
            array('Test' => 'page.test')
        )
    )
)
```

Am I correct in thinking that way? If so, then it doesn't seem to be working in my config. Please let me know if I'm misusing this option!

**Comment by bradis** [comment]
Hello please with laravel  5.1 you can make a simple custom page sample because  always I got this error Administrator: You must provide a valid menu item in the home_page option of your config
