### ISSUE TITLE
WYSIWYG bug

### ISSUE THREAD

**Issue by wingfranky** [FrozenNode/Laravel-Administrator#382]
First thanks for the great plugin. This is really nice!

I found bug when I use WYSIWYG , the CKeditor. There is javascript bug for IE9, IE10 and firefox. There are different kinds of error message.

Here are different kinds of bugs:
a. If you keep to click on different rows of datatable, the data cannot be loaded to CKeditor in the edit panel. The editor will be blank.

b. If you click on "create", the previous edit record's data will be loaded to the CKeditor in the edit panel. It is OK for me comparing to the first point.

Thanks again for this amazing plugin.

**Comment by FrostyX** [comment]
Thank you @adamscybot for quick hack.

It works great when editing yet existing objects. But unfortunately, when I am trying to create new object, I encounter two issues.

1) When I open any existing object, then click to Create New, the wysiwyg editor is filled with previous value.
2) When I open <http://127.0.0.1/admin/foo/new> directly, it redirects me to the <http://127.0.0.1/admin/foo/0>
and the wysiwyg editor doesn't appear at all. It shows only basic `text` input.

Any ideas what can be wrong?

**Comment by mp091689** [comment]
I found new bug with wysiwyg.
Example:
There is two fields

'alias' => [
            'title' => 'Alias',
            'type'  => 'text',
            'editable' => false,
        ],
'body' => [
            'title' => 'Content',
            'type'  => 'wysiwyg',
        ],

wysiwyg does not displaying data because of 'editable' option. If delete 'editable' option from 'alias' field' wysiwyg starts work correctly.

and here is some screenshots
http://joxi.ru/a2X4LLbIy3p4E2 - IDE
http://joxi.ru/v29LvvauGJjjMm - result

http://joxi.ru/Q2K5bblf9QgXLr - IDE
http://joxi.ru/Y2L6bbMInzvLbr - result

May be some one knows how to fix this problem?
now using 'visible' option, but I want to display data, not hide... I need 'editable' option...

**Comment by exodusanto** [comment]
I created my fix, in the settings pages editor didn't work, and if i created new element the editor had old values:

var editors = {};
	var reset = false;
	var activeEditor = null;

	/**
	 * The wysiwyg binding makes the field a ckeditor wysiwyg
	 */
	ko.bindingHandlers.wysiwyg = {
		init: function (element, valueAccessor, allBindingsAccessor, context)
		{
			var options = valueAccessor(),
				value = ko.utils.unwrapObservable(options.value),
				$element = $(element),
				editor;

			value = value ? value : '';

			$element.html(value);

			if (options.id in editors)
				editor = editors[options.id];
			else
			{
				if(value == ""){
					$element.ckeditor({
						language : language,
						readOnly : !adminData.edit_fields[context.field_name].editable
					});

					editor = $element.ckeditorGet();
					editors[options.id] = editor;
				}
			}

			if(value == ""){

				// when the editor is loaded, we want to resize our page
				editor.on('loaded', function()
				{
					setTimeout(function()
					{
						window.admin.resizePage();
					}, 50);

					editor.on('resize', function()
					{
						window.admin.resizePage();
					});
				});

				// wire up the blur event to ensure our observable is properly updated
				editor.focusManager.blur = function()
				{
					var observable = valueAccessor().value,
						$el = $('#' + options.id);

					//set the blur attribute to true so we know now to set the editor data in the update method
					$el.data('blur', true);

					observable($el.val());
				}

				// handle destroying an editor (based on what jQuery plugin does)
				ko.utils.domNodeDisposal.addDisposeCallback(element, function (test) {
					var editor = editors[options.id];

					if (editor)
					{
						editor.destroy();
						delete editors[options.id];
					}
				});
			}
		},
		update: function (element, valueAccessor, allBindingsAccessor, context)
		{
			var options = valueAccessor();
	        $(element).html(ko.utils.unwrapObservable(options.value));


	        var config = {};
	        if (!element.populated && ko.utils.unwrapObservable(options.value).length > 0) {
	            element.populated = true;
	            var ck = $('#ck-'+ko.utils.unwrapObservable(options).id);
	            if (ck.length < 1) {
	                ck = $("<div></div>").attr('id','ck-'+ko.utils.unwrapObservable(options).id);
	                $(element).after(ck);
	                ck.siblings('[id^=cke_editor]').hide();
	            }
	            var editor = CKEDITOR.appendTo( ck[0], config, ko.utils.unwrapObservable(options.value));
	            editor.on('change', function (o) {
	                $(element).html(o.editor.getData());
	                valueAccessor().value(o.editor.getData());
	            });
	            editor.on('loaded', function() {
	            	activeEditor = this;
	                window.admin.resizePage();

	                if(reset == true){
	                	reset = false;
	                	activeEditor.destroy();

	                	var ck = $('#ck-'+ko.utils.unwrapObservable(options).id);
			            if (ck.length >= 1) {
			                ck.html("");
			                ck.siblings('[id^=cke_editor]').hide();
			            }

			            var editor = CKEDITOR.appendTo( ck[0], config, ko.utils.unwrapObservable(options.value));
			            $(element).hide();
			            editor.on('change', function (o) {
			                $(element).html(o.editor.getData());
			                valueAccessor().value(o.editor.getData());
			            });
			            editor.on('loaded', function() {
			                window.admin.resizePage();
			            });
			        }
	            });
	        }

	        if(ko.utils.unwrapObservable(options.value) == ""){
	        	reset = true;
	        }
		}
	};
