### ISSUE TITLE
Can't upload file in edit form

### ISSUE THREAD

**Issue by fverpoest** [FrozenNode/Laravel-Administrator#416]
Hi everyone,

In ourlast application, I used the file-type for one off the fields.

Actually I can't upload a new file in the edit screen. When I create a new entry, there's no problem to upload my file. Before I submit the entry, it stays possible to change my uploaded file.

When I edit my entry, is it not possible to change the uploaded file. There's notting happening when I click 'Upload file'. Deleting the file is possible, but upload a new one is disbled.

I use Firefox v. 20.0 on Win XP. I did also a test on Linux Ubuntu with Firefox 25.0.1. There I have no problems, but I can't update the Firefox v. 20.0 on our Win XP. The Firefox comes with our company-application. We are not allowed to make changes in these packages.

Is it possible to use the upload-form in Firefox v. 20?

**Comment by eliejulz** [comment]
If anyone needs to fill out a DMV notice of vehicle sold, I found a blank form here: http://pdf.ac/6LKvt
