### ISSUE TITLE
Keyed relationship accessor

### ISSUE THREAD

**Issue by beaulm** [FrozenNode/Laravel-Administrator#431]
When editing relations, is it possible to display something different than you save? For instance, I'd like to make an accessor method which returns an associative array and have the dropdown display the value but save the key.

In the examples you use the "name" accessor which concatenates the first and last name of a user, and that must be the way it's being saved as well. No? Would it be possible to have the getter return something like: array(1 => 'John Wayne');

**Comment by davemathews** [comment]
not at this time.
