### ISSUE TITLE
Self pointing relationship

### ISSUE THREAD

**Issue by SergeyMiracle** [FrozenNode/Laravel-Administrator#474]
Hi, i'm trying to make work this

``` php
public function parent()
    {
        return $this->hasMany('Category', 'id', 'parent_id');
    }

    public function children()
    {
        return $this->belongsTo('Category', 'parent_id', 'id');
    }



'columns' => array(
        'id',
        'name_ru',
        'name_en',
        'parent_id' => array(
            'relationship' => 'parent',
            'select' => '(:table).name_en',
            ),
        ),
```

Got no results tho.... Can u help a bit, how it can be done with administrator?

**Comment by sergiocastrovale** [comment]
@SergeyMiracle can you explain how? I'm trying to a self-referencing FK (parent_id) and so far I didn't find any way to save my data.

**Comment by SergeyMiracle** [comment]
@sergiocastrovale it was sooo long time ago... And i'm not using it anymore, so i think i can help u :) sorry
