### ISSUE TITLE
[Help] Use with Auth::basic

### ISSUE THREAD

**Issue by spaceemotion** [FrozenNode/Laravel-Administrator#497]
I want to use administrator for a very small project (just a portfolio site) where just one or two people upload some photos every now and then.

Using Auth::basic should be the way to go I thought, and now I'm having trouble allowing the access to it. the permission closure expects either true or false, overwriting the route doesn't work either (check auth first, then redirect to administrator).

How do I allow access using the basic auth in this case?

**Comment by SwissWeb** [comment]
Simpler, for people who see this in the future 
```php
Route::get('auth/login', ['middleware' => 'auth.basic', function() {
    return redirect()->to('admin');
}]);
```

and set this config in administrator.php
```
'login_path' => 'auth/login',
```
