### ISSUE TITLE
[Enhancement] Add 'not_null' filter to include trashed (soft deleted) models

### ISSUE THREAD

**Issue by spaceemotion** [FrozenNode/Laravel-Administrator#505]
Using [query filters](http://administrator.frozennode.com/docs/model-configuration#query-filter) I can also include trashed models, but on a general basis. I would like to be able to add a query filter based on a selected filter, or a completely different approach: add a new ``not_null`` filter to include the trashed ones as well.

**Comment by davemathews** [comment]
you can do these just programaticlly in the query filter.
