### ISSUE TITLE
GROUP BY issue within DataTables.php when using PostgreSQL

### ISSUE THREAD

**Issue by PadreMontoya** [FrozenNode/Laravel-Administrator#508]
I attempted to use Administrator out of the box on my PostgreSQL database.  Once I got the model wired up, I kept hitting a crash due to trying to due a GROUP BY id when the query was doing SELECT table.*.

In MySQL, doing this is legal: "SELECT * FROM user GROUP BY id".

In PostgreSQL and most other query languages, it is not.

To fix the issue, I went into DataTables.php and changed line 119 from:

$query = $model->groupBy($table . '.' . $keyName);

to

$query = $model->query();

That fixed the problem (with unknown side-effects) and now things seem to be working fine.

**Comment by davemathews** [comment]
This package was written for Mysql so while most features work on postgres some are just not there. sorry.
