### ISSUE TITLE
Proposed architecture for version 5

### ISSUE THREAD

**Issue by janhartigan** [FrozenNode/Laravel-Administrator#528]
Each Viewable thing (action, page, field, column, etc.) will have to implement the `ViewableInterface` which will return things like path information to JS, CSS, Angular directive name, et al. Just about everything will be extensible and in the IoC container, making it trivial to alter just about everything (like the templates used for any of the Viewable things).

Down with Knockout. Long live Angular. Some of my goals for the front-end:

- Custom fields! I've thought for a long time about this and I've settled on using the IoC container to build any custom field classes that developers want to use. These classes should provide all the information about where the Angular directive lives. This means it will be easy to create your own Administrator fields and publish them through composer.
- Deep-nesting of directives (possibly finally allowing for HasMany/HasOne fields)
- Sharing information between fields
- Since you now have access to interface with Administrator through Angular and Laravel, custom fields can effectively do anything
- More complex/interactive data grid
- User-configurable display options in the UI
- Templating using Angular directives

This is currently a very rough sketch and development has already started on the v5 branch. It's likely to change.

```
Manager
Page
	Page => OptionableTrait, ViewableInterface
	Types
		Eloquent
			Page => extends Page\Page
			Controller
			Actions
				Save
				Delete
		Settings
			Page => extends Page\Page
			Controller
			Actions
				Save			
		Custom
			Page => extends Page\Page
			Controller
Menu
	Menu => OptionableTrait, ViewableInterface
Grid
	Grid => ViewableInterface
	Pager
	ItemsPerPager
	Columns => OptionableTrait, ViewableInterface
		Relationships
			Relationship
			BelongsTo
			BelongsToMany
			HasOneOrMany
		Column
Actions
	Action
	Factory
Field
	FieldServiceProvider
	Field => OptionableTrait, ViewableInterface
	Factory
	Types
		Relationships
			Relationship
			BelongsTo
			BelongsToMany
			HasOne
			HasOneOrMany
			HasMany
		Bool
		Color
		Enum
		Factory
		Field
		File
		Image
		Key
		Number
		Password
		Text
		Time
Routing
	Controllers
		Base
		Admin
	Filter
	routes.php
Support
	Facades
		Administrator => points to Manager
	Traits
		OptionableTrait
Validation
	Validator
View
	Composer
	ViewableInterface
```

**Comment by amanpatel** [comment]
I dont' want to hijack any of this, but I worked on the HasMany relationship edit capability. I've generted a pull request for this. I had an immediate need for it because I needed a backend for Question/Answer (quiz) editor. And it was silly to require users to go to the "answers" entity, and ask them to add new answers one by one selecting the question they "belongTo".

It's much more straightforward to have the answers show up in the question form (since a question hasMany Answers).

**Comment by plmarcelo** [comment]
Hi amanpatel,

Do you have any example how can I use your new feature?

Thanks,
Pedro

**Comment by amanpatel** [comment]
@plmarcelo There's nothing special needed. You need to use my copy of laravel administrator until the pull request is accepted and merged (you can do this by putting the following line in your composer.json file):
``
    "repositories": [
        {
	        "type":"git",
            "url": "https://github.com/amanpatel/Laravel-Administrator.git"
        }
``

and later in the require segment:

``
	"require": {
		"frozennode/administrator": "dev-hasmanyVersion",
``
