### ISSUE TITLE
Constraint not working

### ISSUE THREAD

**Issue by brajmohans** [FrozenNode/Laravel-Administrator#548]
'edit_fields' => array
(
    'country' => array(
        'title' => 'Country',
        'type' => 'relationship',
        'name_field' => 'name',
    ),
    'state' => array(
        'title' => 'State',
        'type' => 'relationship',
        'name_field' => 'name',
        'constraints' => array('country' => 'states') //this is the important bit!
    ),
)

I have same country and state setup in my project, and I want to constraint the state for my city model. all relationships are defined exactly like given in example, but when I am selecting country, states are not getting filtered.

**Comment by robsondantas** [comment]
Did you  manage to get it working ? Facing the same issue with laravel 5. Constraint not being even called.
