### ISSUE TITLE
Filter for value in relationship

### ISSUE THREAD

**Issue by stormsson** [FrozenNode/Laravel-Administrator#555]
Hello, i would like to make a question: 
I have 2 tables:
Post - comment    (Post has many comments , comment belongs to post ).

I have made the admin generator for the Post model.

i would like to make a filter to select only the post with approved comments, like
"select \* from post inner join comments on (blahblah) where comments.approved = true "

is there a way to achieve this ?

**Comment by Qsinzheng** [comment]
@janhartigan ,
Has nested-relationship-filter feature been implemented?
