### ISSUE TITLE
Javascript error when refreshing page on "new" action

### ISSUE THREAD

**Issue by louim** [FrozenNode/Laravel-Administrator#557]
Hello!

I got this problem, whenever I refresh the admin page while the "new" form is open, ex:
http://localhost:8000/admin/promotional_materials/new, I get a javascript error and the full page refuse to render.

The error is : "Uncaught SyntaxError: Unexpected token ," (screenshot will explain better than me)
![capture decran 2014-04-07 a 14 21 17](https://cloud.githubusercontent.com/assets/923718/2635131/fc7aaff4-be81-11e3-8473-ab83d002ae08.png)

If I delete the /new, refresh and click the "add new" button, it works as intended.

Forgot to mention that I'm using the latest code version: v4.11.2
If there's anything else that I can do to help debugging, let me know.

Thanks!

**Comment by ZAZmaster** [comment]
Have some error...
![2015-10-07 15-54-44](https://cloud.githubusercontent.com/assets/7642406/10335680/eb559b96-6d0b-11e5-9650-70840b776db6.png)
