### ISSUE TITLE
Resetting a date/datime to null

### ISSUE THREAD

**Issue by zippex** [FrozenNode/Laravel-Administrator#562]
Hi, 

I have a problem when trying to reset a date/datetime field in edit mode. My date field is "nullable" in the database but simply deleting the old date in the input field (in edit view) does not work.

I created a Mutator method in my model to check, if the submitted value is an empty string and tried to set the attribute value to null manually. Then after a while I noticed, that the Mutator is not called when the date field is empty (a dd($value) within the Mutator method never shows up for an empty string but work for a valid date value). 

Do I miss something? Is there a kind of javascript validation before the request is sent to the model and does this validation "eliminates" my empty string value? 

I am very grateful for a hint!
Kind regards
zippex :)

**Comment by ziming** [comment]
+1 for this too, need to be able to set time field to null.

**Comment by davemathews** [comment]
I merged this in to v4.16.6 and v5.0.2
