### ISSUE TITLE
home_page option being a page not working

### ISSUE THREAD

**Issue by jgy3183** [FrozenNode/Laravel-Administrator#567]
When configuring the home_page option to be a menu option that is a page, I get the following exception:
"InvalidArgumentException
Administrator: You must provide a valid menu item in the home_page option of your config" 

Menu Options:

``` php
'menu' => array(
        'Main' =>  'page.administrator.home',
        'navigation',
        'Category Managment'=> array(
            'categorypage',
            'category_settings'),
        'product_settings',
        'productregistration',
        'newsletter'
    ),
```

How I am configuring my home_page option:

``` php
'home_page' => 'Main',
```

I did a little "digging" and I'm not sure if the AdminController is accounting for a "page" menu option as the default.

Just thought I'd throw this out there.  I wanted to have a "landing" page upon logging into the admin section. 

[Edit:1]
[code]
I have configured the following view in views/administrator/home.blade.php:

``` html
<style>
    .admin-container{
        margin:4em 2em;
    }

</style>
<div class="admin-container">

    <h1>Welcome to Bella Administration!</h1>

</div>
```

AND loading that option from the menu bar does render the view properly, however it won't allow that as the home_page option
[code]
[End Edit:1]

Thanks.
Sincerely
John Youngman
Atlanta, GA

**Comment by notflip** [comment]
It's not working with lowercase: main, why is this issue closed? I'm having the same issue. Thank you
