### ISSUE TITLE
Images now showing or downloaded corrupted

### ISSUE THREAD

**Issue by pmaculan72** [FrozenNode/Laravel-Administrator#676]
Hi,

All images that I try to use inside a model configuration are not shown correctly on the browser.

When I try to get the image location and paste it on another browser window, the image is downloaded corrupted.

Using an hex editor and comparing the original image and the downloaded image the only difference is a OA ( line feed ) included as the first byte of the downloaded image.

Any idea on what is may causing this problem?

Thanks,

Paulo

**Comment by stevenbouma** [comment]
Thanks, this is very userful information
