### ISSUE TITLE
Listing table rows INCLUDING soft deleted

### ISSUE THREAD

**Issue by sergiocastrovale** [FrozenNode/Laravel-Administrator#705]
Pretty much what the title says. I am trying to do the equivalent of User::withTrashed(), but I'm not being able to do so. How can I run a query_filter that captures both deleted AND not deleted? It seems that if I try to fetch i.e. only the deleted ones, the resulting query is overwritten anyway and never fetches the deleted ones.

**Comment by triopter** [comment]
Even if the list shows soft-deleted records, you can't open them up to view all their fields (let alone to undelete them) -- clicking the row results in a "create new" form instead.
