### ISSUE TITLE
Latest Changes do not allow a record with 'unique' fields to update

### ISSUE THREAD

**Issue by jmichaelterenin** [FrozenNode/Laravel-Administrator#728]
Updating a record that uses the 'unique' validator for a specific field breaks the ability to 'Update' the record in Administrator.

**Comment by judgej** [comment]
Not sure if it has been noted, but you don't need to pass in the value of the ID to ignore to the validation string. You can use the pseudo column :id and that will be automatically substituted at the time it is validated.

For example, I have a "code" column that must be unique in the "clients" table, so the validation rule is:

    "unique:clients,code,:id"

That works for me on L5.0

How the static property shown in "the trick" above allows the use of $this to define it, has stumped me totally. How is that even valid PHP?
