### ISSUE TITLE
Latest Changes do not allow a record with 'unique' fields to update

### ISSUE THREAD

**Issue by jmichaelterenin** [FrozenNode/Laravel-Administrator#737]
Set a field within your model as unique, like so:
~~~
class District extends Eloquent {

/**
 * Ardent validation rules
 */
    public static $rules = array(
      'country_id' => 'required',     
      'name' => 'required|unique:districts',
    );          

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'districts';
~~~
Then, via Administrator, attempt to Update a field in an existing record other than the unique field, and you won't get an error, but the field won't update.

It just fails in the $model->save inside your Config/Model/Config.php, without displaying any errors. Apparently your solution was to remove the fields that weren't being updated, but that still causes a failure within Ardent's validation.

This should be easily reproducible, please let me know if you need anymore info.

**Comment by davemathews** [comment]
this is an error with the model.  Look into the "sometimes" validation for those unique rules and how to pass the id to them also.
