### ISSUE TITLE
Error while using relationship column : maximum function nesting level reached.

### ISSUE THREAD

**Issue by vishwajeetv** [FrozenNode/Laravel-Administrator#748]
My Ardent model has a has_one relationship like this

    public static $relationsData = array(
    'organization'  => array(self::HAS_ONE, 'Organization', 'foreignKey' => 'party_id'),
    );
Now, my Laravel Administrator package's model config file have column configuration like this

    'columns' => array(
    'id',
    'organization' => array(
        'title' => "Organization",
        'relationship' => 'organization', //this is the name of the Eloquent relationship method!
        'select' => "(:table).organization_name",
        ),
    'address' 
    ),
Now, it is throwing an error like this

Maximum function nesting level of '100' reached, aborting! Open: C:\xampp\htdocs\hrms\vendor\laravel\framework\src\Illuminate\Support\Str.php

    * Convert a value to studly caps case.
    *
    * @param  string  $value
    * @return string
    */
    public static function studly($value)
    {
        $value = ucwords(str_replace(array('-', '_'), ' ', $value));

    return str_replace(' ', '', $value);

**Comment by vlafranca** [comment]
Hi everyone,
This fix did not works for me ... I'm trying to access a nested relation ship from belongsTo to hasMany, and i have exactly same symptoms as before (allowed memory size) as before ...
Do you have any idea ?

Thanks

**Comment by vjandrea** [comment]
Same problem here and same symptoms, has anybody found a solution?
