### ISSUE TITLE
how to config an accessor in edit_fields?

### ISSUE THREAD

**Issue by Gwill** [FrozenNode/Laravel-Administrator#762]
My Model like this:
```
    public function getAbstractAttribute() {
        if ($this->attributes['abstract']) {
            return $this->attributes['abstract'];
        }
        else {
            return substr($this->attributes['content'], 0, strpos($this->attributes['content'], '<!--more-->'));
        }
    }

    public function setAbstractAttribute($value) {
        $this->attributes['abstract'] = $value;
    }
```

And the Model config:
```
    'edit_fields' => array(
        'abstract' => array(
            'title' => 'Abstract',
            'type' => 'wysiwyg',
        ),
    ),
```

when I enter the model admin page, it says `Undefined index: abstract` .
What's wrong?

**Comment by arall** [comment]
Check this: https://github.com/FrozenNode/Laravel-Administrator/issues/551#issuecomment-61023921

**Comment by Modifikator** [comment]
I have also this error, has anyone found a solution how to fix it?

**Comment by davemathews** [comment]
if you want an accessor to return a value, you need to add it to the $appends property in your eloquent model (it's the very last thing that's mentioned in the Eloquent docs).
