### ISSUE TITLE
Can't use whereHas in query filter

### ISSUE THREAD

**Issue by ssfinney** [FrozenNode/Laravel-Administrator#773]
When I attempt to use the ```$query->whereHas``` method in a query filter, I get an exception:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'has' in 'where clause' (SQL: SELECT 

COUNT(id) AS aggregate FROM (select `scores`.* from `scores` where `scores`.`deleted_at` is null and 

`has` = person and `deleted_at` is null group by `scores`.`id`) AS agg)
```

Here is my code:

```php
    'query_filter'   => function ($query) {
        return $query->whereHas('person', function($q) {
                     return $q->where('special_number', '>', '0');
            })->whereNull('deleted_at');
    },
```

It appears that something is trying to parse ```whereHas``` like it would with ```where<property>```, treating the word "has" as a property on the model.

I've temporarily worked around this by doing "join" statements to filter what I want manually.

**Comment by davemathews** [comment]
@ssfinney screw wherehases :)
