### ISSUE TITLE
search_fields with relationships

### ISSUE THREAD

**Issue by arall** [FrozenNode/Laravel-Administrator#774]
Hi there,

I have been reading the documentation and I'm not able to use 'search_fields' with relationships.
Here is my case:

I got 3 tables: `Orders`, `Departs` and `Locations`.
Here are the relationships:

Order:
```php
public function depart() {
    return $this->belongsTo('Depart', 'depart_id');
}
```

Depart:
```php
public function orders() {
    return $this->hasMany('Order');
}
public function fromLocation(){
    return $this->belongsTo('Location', 'from_location_id');
}
public function toLocation(){
    return $this->belongsTo('Location', 'to_location_id');
}
```

And the Administrator `Order` model `Depart` field config:
```php
'depart' => array(
    'title' => 'Depart',
     'type' => 'relationship',
     'name_field' => 'title', //Depart accessor (depart->fromLocation->name & depart->toLocation->name)
     'autocomplete' => true,
),
```

Obviously, the autocomplete isn't working, since the query is searching for 'title' field.
My question is: How can I query the related tables (departs -> locations) using the 'search_fields' attribute? Is there a better way to do this?

Thanks

**Comment by davemathews** [comment]
http://administrator.frozennode.com/docs/field-type-relationship#large-datasets-and-autocomplete
