### ISSUE TITLE
Enum filter with numeric values

### ISSUE THREAD

**Issue by arall** [FrozenNode/Laravel-Administrator#776]
Hi there,

Is there any way to do a filter like this?

```php
'season' => array(
    'type' => 'enum',
    'title' => 'Season',
    'options' => array(
        1 => 'Winter',
        2 => 'Spring',
        3 => 'Sumer',
        4 => 'Fall',
    ),
),
```

Here is the build function on Enum field class:
```php
//iterate over the options to create the options assoc array
foreach ($dataOptions as $val => $text)
{
	$options['options'][] = array(
		'id' => is_numeric($val) ? $text : $val,
		'text' => $text,
	);
}
```

So if the key is numeric, will allways use the text as value.

**Comment by futurewebsites** [comment]
I have the same issue :(

**Comment by hackel** [comment]
This is a really frustrating issue.  As a really awful work-around, I added a leading zero to my numeric keys like so:
```php
			'options' => [
				'-01' => 'Expired',
				'00'  => 'Disabled',
				'01'  => 'Enabled',
			],
```
This doesn't allow displaying the correct value in the edit form, but it can at least be set to the correct value.

As a possible solution, perhaps adding an option `'enum_keys` => 'numeric'` to the field itself would make sense, in order to preserve backward compatibility?  Just a thought.

**Comment by frzsombor** [comment]
That's a great idea! Thanks!

**Comment by frzsombor** [comment]
I just found an other - really hacky, yet working - workaround without modifying the source of Administrator. Simply changing the keys to a string is not helping, but adding a space at the end of them does the trick. However I had no time to check why it works and I don't know how long this _hack_ will last.

```php
'filters' => array(
    'featured' => array(
        'title' => 'Featured',
        'type' => 'enum',
        'options' => array(
            '0 ' => 'No',  //notice the space in the key 
            '1 ' => 'Yes', //notice the space in the key
        ),
    ),
),
```

**Comment by narutooturan** [comment]
@frzsombor it works with edit_fields.
