### ISSUE TITLE
Fails to serialize model when model has an attribute that references the same relation displayed in a column

### ISSUE THREAD

**Issue by BenjaminRH** [FrozenNode/Laravel-Administrator#780]
When you have Model A, and Model A both displays Model B's name as a relationship column and also has an accessor that references Model B, I get the following error:

    Failed calling ModelB::jsonSerialize()

**Comment by davemathews** [comment]
yes you can test in the accessor for empty attribute and return to fix this, its because administartor loads an empty model to do the create then fills it.
