### ISSUE TITLE
password match

### ISSUE THREAD

**Issue by anothergituser** [FrozenNode/Laravel-Administrator#783]
Hi, 
I use these rules in my User model when i create an user
```
public static $rules = [
		'name' => 'required',
		'email' => 'required|email|unique:users',
		'password' => 'required',
		'password_repeat' => 'required|same:password',
		'language' => 'required'
	];
```
In my administrator user model i have
```
        [ 'password' => [
			'title' => trans('backend.password'),
			'type' => 'password',
		],
		'password_repeat' => [
			'title' => trans('backend.password'),
			'type' => 'password',
		],
```
but when creating it says they do not match.

Using just password without password_repeat works as expected.
Question is, can we use administrator to create fields that need to match other fields?

**Comment by Derrick91** [comment]
May i know how did you solved this?
