### ISSUE TITLE
ckeditor upgrade?

### ISSUE THREAD

**Issue by jonstavis** [FrozenNode/Laravel-Administrator#785]
There is a ckeditor bug in Safari 7 that moves the cursor back to the beginning of the first line of the editor when enter is pressed.  Some more info plus documented fix is here:

http://ckeditor.com/blog/CKEditor-4.4.5-Released

Although Laravel-Administrator's composer.json calls for ckeditor 4.*, it appears that the version getting written to public/js/ckeditor is 4.3.3.

Is this a correct assumption, and is there any plan to update to a version of ckeditor that includes this fix?

Thanks!

**Comment by frzsombor** [comment]
There are already a few problems with CKEditor and Knockout callbacks and timeouts "interferencing", if you search the issues. Not sure if updating CKEditor (or Knockout) would increase or reduce the number of these bugs. But someone with the appropriate knowledge should really take a look into this.

**Comment by anothergituser** [comment]
agree
