### ISSUE TITLE
Uploading Image to amazon using s3

### ISSUE THREAD

**Issue by devmtnaing** [FrozenNode/Laravel-Administrator#786]
Please guide me proficient way to upload images to amazon instead to public path. 

sample codes would be more helpful.

**Comment by sergiocastrovale** [comment]
I'm trying to work on this too. Any ideas? I need to detect whenever an image is being uploaded to my server, and then make a copy of it to S3.

**Comment by davemathews** [comment]
Look into the Eloquent Eventing: http://laravel.com/docs/5.1/eloquent#events
