### ISSUE TITLE
getNameAttribute / getFullNameAttribute typo in documentation

### ISSUE THREAD

**Issue by ghost** [FrozenNode/Laravel-Administrator#790]
You have a typo docs - both [github](https://github.com/FrozenNode/Laravel-Administrator/blob/master/docs/field-type-relationship.md) and the [webiste](http://administrator.frozennode.com/docs/field-type-relationship) texts are referring to *getFullNameAttribute()* Eloquent accessor, but in your examples you have *[getNameAttribute()](https://github.com/FrozenNode/Laravel-Administrator/blob/master/examples/app/models/Actor.php#L22)*.
While it's simple, it was a little confusing to find the truth :)

**Comment by frzsombor** [comment]
+1

**Comment by davemathews** [comment]
fix is coming in just a but thanks.
