### ISSUE TITLE
Typing in non-numeric text for a type=number field with integer or numeric validation in model does not fail

### ISSUE THREAD

**Issue by BenjaminRH** [FrozenNode/Laravel-Administrator#793]
Typing in non-numeric text for a type=number field with integer or numeric validation in model does not fail. So if I have a field called "age" with type of "number" and in the model it's validated as either "integer" or "numeric", typing in "foobar" in the create/edit form should give me a validation error. Instead, it saves, as if I did not enter any text at all.

**Comment by frzsombor** [comment]
Number type fields are "validated" front-end only by default, and by validation I mean if you enter any non-numeric input, it will be removed (or if it starts with a number like "10 years old", " years old" will be removed by JS. If you are afraid of that someone will send invalid data to the database on purpose, you should use validation. See: http://administrator.frozennode.com/docs/validation

**Comment by BenjaminRH** [comment]
Ah, that clarifies things. So, I am using validation. But I think removing any non-numeric input is incorrect behavior. This means that if they enter text or something, not necessarily maliciously, it will be submitted to the database as being empty, and thus will not trigger any validation to tell them what they did wrong if the field is not required.

**Comment by frzsombor** [comment]
Well yes, maybe it is not the best solution, but a simple filtering script (that allows only numbers to be entered) can also be bypassed by users if they copy-paste strings, or use keycodes with Alt+NumPad, etc. Of course the validation could run on different events but I think using a bulletproof frontend validation is not a goal of administrator. However you can submit a PR if you make any good implementation. Also in the meantime you can use the [description](http://administrator.frozennode.com/docs/fields#description-option) to tell the users to use numbers only.

**Comment by BenjaminRH** [comment]
You've misunderstood me. I am not advocating better client-side validation. I'm saying the current behavior wherein anything that's not a number for type=number fields is removed before being submitted is incorrect; the field should be submitted with whatever the user entered, to allow the server-side validation to work.

**Comment by frzsombor** [comment]
Oh, I understand you now, sorry!
If you want something like this, how about forgetting the number field type, and using a simple text type, setting up [validation](http://administrator.frozennode.com/docs/validation) with rules from [Laravel's available validation rules](http://laravel.com/docs/4.2/validation#available-validation-rules)? You can also provide custom error messages.

**Comment by BenjaminRH** [comment]
Yeah, that's what I've ended up doing. Thanks!
