### ISSUE TITLE
Hidden field

### ISSUE THREAD

**Issue by arall** [FrozenNode/Laravel-Administrator#796]
There is any way to send a hidden field on model edit?

**Comment by frzsombor** [comment]
I don't know what you are trying to achieve, but maybe you can solve this by using Eloquent's `saving` and `updating` events. Example: http://stackoverflow.com/a/18123215/2953830

**Comment by janhartigan** [comment]
This exists with the visible option. The section in the docs actually uses this exact example:

http://administrator.frozennode.com/docs/fields#visible-option
