### ISSUE TITLE
Validator::validateString() conflicting with Laravel core

### ISSUE THREAD

**Issue by tbesiktasli** [FrozenNode/Laravel-Administrator#806]
Hello!

Making an update today via composer, i got a "Declaration not compatible" between the validateString() method of the Validator class of Administrator and the Laravel Framework itself.

The method signature is different. In the Laravel core class there is no $parameters parameter. Removing it solves the problem indeed.

Best regards,
tbesiktasli

**Comment by adampdarcy** [comment]
Hi, just did composer update and not fixed the issue.

BadMethodCallException
Method [validateString] does not exist.

**Comment by adampdarcy** [comment]
Fixed by adding this method to https://github.com/FrozenNode/Laravel-Administrator/blob/master/src/Frozennode/Administrator/Validator.php

public function validateString($attribute, $value, $parameters)
    {
        return is_string($value) || is_callable($value);
    }

**Comment by brunocascio** [comment]
Hi!

Not fixed.

I use laravel 4.2, still same error:

![captura de pantalla de 2015-01-30 14 15 30](https://cloud.githubusercontent.com/assets/2397875/5979939/b6f9f644-a88a-11e4-9ee9-a2d1291e6552.png)

Rollback to 4.6.1 and it works.

**Comment by janhartigan** [comment]
Taking a look at this now.

**Comment by janhartigan** [comment]
[Should be fixed now](https://github.com/FrozenNode/Laravel-Administrator/commit/62f8c18c7c649a71e5c2d05a58aa4cde8bee9b4d) for all versions of Laravel.

**Comment by brunocascio** [comment]
Yes, it's work!! Thanks!

**Comment by adampdarcy** [comment]
Brilliant, thanks guys!!
