### ISSUE TITLE
is there any way to disable new 'collection' button?

### ISSUE THREAD

**Issue by nickfan** [FrozenNode/Laravel-Administrator#809]
is there any way to disable new 'collection' button?

for example:
i don't want to create trade order from administrator panel.

**Comment by frzsombor** [comment]
In model configuration, the action_permissions option lets you define permissions on the four primary actions: 'create', 'update', 'delete', and 'view', and any custom actions that you define.
Read more: http://administrator.frozennode.com/docs/model-configuration#action-permissions

**Comment by nickfan** [comment]
thank you very much. i see.
