### ISSUE TITLE
RTL Support?

### ISSUE THREAD

**Issue by iturki** [FrozenNode/Laravel-Administrator#814]
Hi.
I read [here](http://www.tutorialworld.net/admin-package-laravel-4/) that Administrator has RTL support but I couldn't find a way to do so.
* Changing the Laravel locale to a RTL language (in the app/cpnfig/app.php) translates the strings only, which is expected.
* Adding `dir="rtl"` to the body tag in `default.blade.php` file DOES reverse the layout, partially at least. The site name (the Admin word in the top left corner) and the create button stay in their positions.

So, is this an issue in my installation only or was I misinformed about the Administrator RTL support?

**Comment by janhartigan** [comment]
That link is for the [Syntara Admin](https://github.com/MrJuliuss/syntara), not this one. RTL isn't currently available in Administrator out of the box, unfortunately, but as always, you have complete control over what css gets dumped onto the page via this view composer: https://github.com/FrozenNode/Laravel-Administrator/blob/86ea73d4b0a5a2fa1c39d443d978f53a24a88fdf/src/viewComposers.php#L70
