### ISSUE TITLE
Date field format

### ISSUE THREAD

**Issue by fernando1419** [FrozenNode/Laravel-Administrator#815]
Hi, I have a date field called birth_date and I have the following settings for it in edit_fields section:
birth_date' => array(
                            'title'       => 'Born (dd/mm/yyyy)',
                            'type'        => 'date',
                            'date_format' => 'dd/mm/yy',
                    ),
The problem I have is that this field is not showing the date like '05/12/2004' but instead it shows '2004-12-05' and also it shows the current date as selected date in datepicker while it should show '05/12/2004' as selected date.
Any ideas why this is happening?.
Thanks in advance.

**Comment by davemathews** [comment]
you need a getter to format the saved date into the correct format for displaying in the field in administartor.
