### ISSUE TITLE
Select field values without relationships.

### ISSUE THREAD

**Issue by fernando1419** [FrozenNode/Laravel-Administrator#818]
Hi, is there any way to manage model's field values as an associative array in a select field control?.
For instance, let's suppose we have:
- League Model representing a leagues table in DB 
- leagues table in DB with a field called "status".
- 2 constants defined in my model:
const STATUS_STARTED = 1;
const STATUS_FINISHED = 2;

I would like to have in the edit_fields section of laravel administrator a select field control with the values: (started, finished) so when I select the value "started" and press save the League Model stores 1 in the status field of leagues table or 2 when selecting the value "finished".
I know this issue could be accomplished with relationships but I don't need to define relationships in this case. Could this be possbile?.
Thanks in advance.
Fernando.

**Comment by TrustOkoroego** [comment]
i am having the same issue

**Comment by davemathews** [comment]
you could just use an Enum on the model config in administrator.
