### ISSUE TITLE
How to check permission.

### ISSUE THREAD

**Issue by baoviet3010** [FrozenNode/Laravel-Administrator#825]
For example. I have table `groups`. User in group Admin has full permission. In group Author user can add new post.
So, how to check permission to show, hide / enable, disable action on Model.
Thanks and sorry for my bad English.

**Comment by janhartigan** [comment]
http://administrator.frozennode.com/docs/configuration#permission

http://administrator.frozennode.com/docs/model-configuration#action-permissions

**Comment by baoviet3010** [comment]
Thanks you, Solved!
