### ISSUE TITLE
Frozenode File upload Issue Http Error

### ISSUE THREAD

**Issue by TrustOkoroego** [FrozenNode/Laravel-Administrator#833]
I am using frozenNode to administer a website. but each time i try to upload a larger file i kept getting http error, i checked the server error from the ajax response and found this.
![image](https://cloud.githubusercontent.com/assets/10142399/6527793/e7f5dc50-c41d-11e4-945e-223136201ec3.png)

please have anyone had this issue before. The confusing part is that it uploads files of lower size, and i have increased php maximium upload size setting in php.ini file.

**Comment by janhartigan** [comment]
It's possible that your server has in-built limits to the size of a file upload. Check with your host and then try to pinpoint the exact file size threshold at which you begin to see this error.

**Comment by TrustOkoroego** [comment]
Thanks for the response. I am using wamp server on a Windows matchine. I have another application that uploads file of any size without any issue which coded myself. I had to deploy it to my Linux server a shared hosting, hoping the issue won't persist but instead I got another error
