### ISSUE TITLE
one to one relation attributes

### ISSUE THREAD

**Issue by hardikaecor** [FrozenNode/Laravel-Administrator#834]
I am facing one issue, and couldn't find anywhere on document that how to handle this.

I have a 'users' table and 'persons' table, 'users' have all basic information and 'person' table have detailed information of user.

the 'users' table has one 'person_id' field which points to id of 'persons' table.
now in my User.php model i have a relationship defined as follows

```php
    public function details(){
         return $this->belongsTo('App\Person','person_id');
    }
``` 
i want to have combined edit fields in Admin side. so i have created file users.php for Administrator which has following 'edit_field' settings

```php
             'edit_fields' => array(
			'username' => array(
				'title' => 'Username',
				'type' => 'text',
			),
			'email' => array(
				'title' => 'Email',
				'type' => 'text',
			),
			'details' => array(
				'title' => "First Name",
				'type'       => 'relationship',
				'name_field' => 'first_name',
			),
			'is_confirmed' => array(
				'title' => "Is Validated",
				'is_confirmed' => 'username',
				'type' => 'bool'
			)
		),
```

there are 2 problems I am facing.
1. the first name field comes as select box where I want a text box
2. I want to add last name editable field too. But can't get how can I add that.
It would be great help if i can get some solution.

**Comment by deep88** [comment]
i am facing the same problem.. :(

**Comment by ChristianNobis** [comment]
I'm searching for an similar solution to edit and relatet models in Place. Not only for an 1to1 relationship but also for 1tomany. For example havin one product and many variations (colors).

**Comment by davemathews** [comment]
you will need to have a custom save on the users model and mutators to pull the data you want to edit into the model. then you can setup the fields the way you need too normally and use the custom save to move data between the tables as needed.
