### ISSUE TITLE
Custom query

### ISSUE THREAD

**Issue by Eduard90** [FrozenNode/Laravel-Administrator#837]
Hello.

I have simple query (for display data in frontend):
SELECT * FROM (
                    SELECT *
                    FROM current_rates
                    ORDER BY rate_update_date DESC
                ) AS t1
                GROUP BY t1.bank_id
                ORDER BY t1.usdrub_s

this query first - sorting rows by rate_update_date, after grouping by t1.bank_id and then sorting by t1.usdrub_s.

How i can execute this query in admin panel?

**Comment by janhartigan** [comment]
Grouping may cause some weird side effects, but you can modify the query before it's run using this:

http://administrator.frozennode.com/docs/model-configuration#query-filter

Tread lightly, though.
