### ISSUE TITLE
align and pasting from word not working in the editor

### ISSUE THREAD

**Issue by TrustOkoroego** [FrozenNode/Laravel-Administrator#839]
i am trying to centralize my post, add color and paste from word document. but its not working.

![image](https://cloud.githubusercontent.com/assets/10142399/6639827/189a0b22-c993-11e4-8b87-0d437e20d8b7.png)

**Comment by TrustOkoroego** [comment]
The issue is the wysiwyg. the version that ships with frozennode is a limited version. i had to download the full version

**Comment by davemathews** [comment]
yes we will plan on updating the wysiwyg to the latest in the distro soon.
