### ISSUE TITLE
Set locales is error in Laravel5

### ISSUE THREAD

**Issue by yuler** [FrozenNode/Laravel-Administrator#847]
I set 'locales' option in administrator.php
``
'locales' =>  array('en', 'zh-TW'),
``

When I click language ,it is error.

FatalErrorException in AdminController.php line 613:
Call to a member function put() on null

**Comment by camiloclc** [comment]
Same here. Seems like the session object passed to the constructor is not assigned to the controller's session var. There's no `$this->session = $session;` there.

**Comment by schrink** [comment]
:+1:

**Comment by arsfeld** [comment]
This affects other sections of the admin, like downloading a file with a custom action (line 237 of AdminController).

**Comment by beysong** [comment]
The same problem! anyone solved it?

**Comment by arsfeld** [comment]
The pull request #856 fixes this. I'm using a private fork with that patch applied for now, not a great solution, but works.

**Comment by beysong** [comment]
not work for me.because the app session con't get the value in https://github.com/FrozenNode/Laravel-Administrator/blob/master/src/Frozennode/Administrator/AdministratorServiceProvider.php#L142

**Comment by davemathews** [comment]
All these are now fixed with v5.0.5
