### ISSUE TITLE
Access to $model inside options_filter?

### ISSUE THREAD

**Issue by jmichaelterenin** [FrozenNode/Laravel-Administrator#849]
I'm aware that the only parameter sent into an options_filter is the $query object. 
Here's my scenario:
i have 5 tables:
thumbnails: id, identifier, title, url, **facility_id**
facilities: id, **entity_id**
services: id, **facility_id**,**entity_id**
entities: id, entity_type ('facility' or 'service')
pivot_table: id, **entity_id**, **thumbnail_id**

*Foreign keys in bold*

An end-user uploads photos to his account. He can then attach photos to either his facility or 1 to N services attached to his facility. They are attached through the pivot table, with a unique entity record for each facility and service. 

On the backend, i have the following relationships in thumbnails:

    public function facility()
    {
        return $this->belongsTo('facility');
    }	
    
    public function owners()
    {
    	return $this->belongsToMany('entity', 'entity_thumbnails');
    }

and the following relationship in entities:

    public function thumbnails()
    {
		return $this->belongsToMany('thumbnail', 'entity_thumbnails')->withPivot('id', 'sort');
    }
	
The edit field inside entities.php reads:

    'thumbnails' => array(
			'title' => 'Thumbnails',
			'type' => 'relationship',
			'name_field' => 'unique_identifier',			
			'sort_field' => 'sort',
    )			

This is providing a dropdown of ALL the thumbnails in the system, and I want to create an options_filter that is able to show only the thumbnails uploaded by the facility owner.
Is there a way to do this through options_filter, or perhaps through a new relationship with a where clause as a restriction to include ONLY the thumbnails owned by the facility? Or a modification of the constraining relationship, except that the initial constraint has already been set?

**Comment by davemathews** [comment]
use the Auth::user() to get the user model and do whatever magic you need ot inside the relationships option filter.

http://administrator.frozennode.com/docs/field-type-relationship#filtering-relationship-options
