### ISSUE TITLE
Update installation guide with info about installing the package on Laravel 5

### ISSUE THREAD

**Issue by anatoliyarkhipov** [FrozenNode/Laravel-Administrator#859]
Information on this page is not actual and does not reflect the Laravel 5 way to publish vendor files (I mean `vendor:publish` instead of `config:publish`):
http://administrator.frozennode.com/docs/installation

I can try to make pull reqest with fix for that, but is seems like source files of administrator.frozennode.com are not in this repo.

**Comment by kinow** [comment]
+1

**Comment by davemathews** [comment]
fixed in the docs, I do not have access to build administrator.frozennode and will change the docs to another domain soon.

**Comment by kinow** [comment]
Thanks @davemathews
