### ISSUE TITLE
Documentations and Video Tutorial for Laravel 5

### ISSUE THREAD

**Issue by mansoorkhan1** [FrozenNode/Laravel-Administrator#861]
It seeems like the documentation provided is only for laravel version 3, in video used version 3, could you please update content and show us its working with laravel 5 along with a detailed documentation.

thanks

**Comment by acacha** [comment]
+1

**Comment by phillipmadsen** [comment]
i would also like to see this.

**Comment by sergiocastrovale** [comment]
Ditto. It's pretty hard to understand what to do in L5 with the new namespaces philosophy and all.

**Comment by davemathews** [comment]
http://administrator.frozennode.com/docs/introduction is up to date and works for L5

**Comment by king724** [comment]
I would also appreciate updates for Laravel 5.1.

Quite a bit has changed. From L4 to L5 and from 5 to 5.1

**Comment by davemathews** [comment]
It works on L5.1 we are using the current v5.0.7 currently on L5.1 so @king724 whats the issue?
