### ISSUE TITLE
Image upload: why don't use a mixed approach for naming?

### ISSUE THREAD

**Issue by axettone** [FrozenNode/Laravel-Administrator#863]
When using an Image field, a user can choose 'keep' to keep the original filename o 'random' for security/collision-avoidance reasons. Why don't add a 'mixed' option? SEO people love to have a relevant name for images, so I think that we can do a great job by adding a 'mixed' option. Its behaviour should be something like:
Original        ======>    Uploaded
mycat.jpg     ======>    mycat-e9fk40h0sk24kv94.jpg
I'd like to make a pull request with this enhancement. What do you think?

**Comment by davemathews** [comment]
let me see the pull request and we will see what it looks like.
