### ISSUE TITLE
large table with 4m rows slow loading

### ISSUE THREAD

**Issue by ustenko** [FrozenNode/Laravel-Administrator#864]
this queries very slow
SELECT COUNT(id) AS aggregate FROM (select `product`.* from `product` group by `product`.`id`) AS agg
EXPLAIN SELECT COUNT(id) AS aggregate FROM (select `product`.* from `product` group by `product`.`id`) AS agg

do you have any solutions or plans to fix this problem?

**Comment by davemathews** [comment]
this is indexing and model issues not Administrator issues.  we are always working to optimize queries though.
