### ISSUE TITLE
belongsToMany filter triggers grouping error in PostgreSQL

### ISSUE THREAD

**Issue by dsshafer** [FrozenNode/Laravel-Administrator#865]
The SQL query generated by filtering on a belongsToMany relationship works on MySQL, but triggers a grouping error on PostgreSQL.

I have users, roles, and role_user tables (used by Entrust). In Laravel Administrator, I have a filter column for users defined as "'roles' => ['type' => 'relationship', 'name_field' => 'name']". If I try to filter users looking for those having role ID 1, I get the following error:

QueryException in Connection.php line 624:
SQLSTATE[42803]: Grouping error: 7 ERROR: column "role_user.role_id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...CT COUNT(id) AS aggregate FROM (select "users".*, "role_user...
^ (SQL: SELECT COUNT(id) AS aggregate FROM (select "users".*, "role_user"."role_id" from "users" inner join "role_user" on "users"."id" = "role_user"."user_id" where "users"."deleted_at" is null and "role_user"."role_id" in (1) group by "users"."id" having COUNT(DISTINCT role_user.role_id) = 1) AS agg)

The error goes away if I 1) switch the DB from PostgreSQL to MySQL, 2) remove role_user.role_id from the inner select list, or 3) add role_user.role_id to the inner group by list, e.g.:

-- Remove role_user.role_id from inner select list
SELECT COUNT(id) AS aggregate FROM (select "users".* from "users" inner join "role_user" on "users"."id" = "role_user"."user_id" where "users"."deleted_at" is null and "role_user"."role_id" in (1) group by "users"."id" having COUNT(DISTINCT role_user.role_id) = 1) AS agg

or:

-- Add role_user.role_id to inner group by list
SELECT COUNT(id) AS aggregate FROM (select "users".* , "role_user"."role_id" from "users" inner join "role_user" on "users"."id" = "role_user"."user_id" where "users"."deleted_at" is null and "role_user"."role_id" in (1) group by "users"."id", "role_user"."role_id" having COUNT(DISTINCT role_user.role_id) = 1) AS agg

**Comment by davemathews** [comment]
yeah sorry about this, Administrator was written for MYSQL and does not play well fully with Postgres
