### ISSUE TITLE
I was just curious if we can delete the image in the folder along with the database record.

### ISSUE THREAD

**Issue by emocentmagar** [FrozenNode/Laravel-Administrator#866]

**Comment by viniciusdaniel** [comment]
I believe this is a task that the Image model, of your application, should take care. 

You can create a Model Observer to take care of the event "deleted" it and delete the file. 

Ideally you can create a queue job to take care of it and not have asynchronous IO delay.

**Comment by emocentmagar** [comment]
I am not fully into Laravel so can you please help me with this queue job thing. I have been trying to implement in my application but have not been able to break it. I will much appreciate if you could explain with an simple example. Thanks, by the way, for replying.

**Comment by davemathews** [comment]
@emocentmagar look into laravel eventing for the cleanup once the database model is deleted: http://laravel.com/docs/5.1/eloquent#events
