### ISSUE TITLE
Image is uploaded before saving the record.

### ISSUE THREAD

**Issue by emocentmagar** [FrozenNode/Laravel-Administrator#868]
So i was playing around with administrator package and I noticed that the image is actually saved in the server before hitting the save button. If user chooses to cancel the entry then the image remains in the server which I think is not a good approach. So is there a way to prevent this? And if there isn't then am I stuck with this?

Anyway thanks for creating such an amazing package.

**Comment by davemathews** [comment]
as of right now you are stuck with it, but you could have a cleanup process take care of it for you, (if images in the folder not in the database table then remove them.) we have to upload the image and make sure its successful before we save the image data to the database. its a chicken and egg situation.
