### ISSUE TITLE
A typo in some keys can cause a blank page with no error

### ISSUE THREAD

**Issue by BenWoodford** [FrozenNode/Laravel-Administrator#869]
Been scratching my head over this one for some time now. Until I noticed one of my filters had a typo in the options. It was a relationship filter and I'd typo'd autocomplete as autocompletel somehow.

This isn't really the sort of bug that should cause a blank page to be returned. Surely if an array key isn't valid it should just be ignored?

**Comment by davemathews** [comment]
@BenWoodford was there any errors in logs?  was it in production env so no whoops page?

**Comment by BenWoodford** [comment]
No errors, no log entries, just a blank page as far as I can recall. I believe it was in production though yeah, but there should be an error somewhere?

**Comment by davemathews** [comment]
@BenWoodford I'm going to close this off and make sure we are returning proper erros.  Thanks.
