### ISSUE TITLE
FrozenNode TokenMismatchException filters.php:78  OSX MAMP

### ISSUE THREAD

**Issue by rollrodrig** [FrozenNode/Laravel-Administrator#870]
Hello.
I was working with laravel frozenNode in window, everthing works fine, now i migrate to Macbook 
I am using local server  Mamp with a virtual host wong.dev
Php 5.4 / tryed with php 5.3 to and 5.5, 5.6
Laravel 4.
frozenNode 4.

I am trying to create a new user with frozenNode admin but when i click "save" nothing happens
Here the laravel.log error

/laravel.log
[2015-05-21 22:25:27] production.ERROR: exception 'Illuminate\Session\TokenMismatchException' in /Applications/MAMP/htdocs/wong/app/filters.php:78

/filter.php line 78
Route::filter('csrf', function()
{
	if (Session::token() != Input::get('_token'))
	{
		throw new Illuminate\Session\TokenMismatchException;
	}
});

/administrator.php
	'permission'=> function()
	{
		// return Auth::check();
		return true; // to login de admin without auth.
	},

Network Screenshot 
![screen shot 2015-05-21 at 5 35 53 pm](https://cloud.githubusercontent.com/assets/12551728/7760326/0af98de8-ffe0-11e4-829f-a01d89ddd98d.png)

Network screenshot token
![screen shot 2015-05-21 at 5 36 14 pm](https://cloud.githubusercontent.com/assets/12551728/7760331/18c1f474-ffe0-11e4-9b3a-77245ae3bfdc.png)

Thanks for any help.

**Comment by gkhachidze** [comment]
I have same issue please any help ?

**Comment by davemathews** [comment]
if still an issue please reopen ticket. trying to clean up the old tickets and get this project back on track.  The above issue looks to be that you are not getting a session saved.
