### ISSUE TITLE
How do I get the settings data?

### ISSUE THREAD

**Issue by emocentmagar** [FrozenNode/Laravel-Administrator#872]
I am using this package with Laravel 4 and I found that the settings data are store in "app/storage/administrator_settings/site.json". Now how do I get the data from this file so that I can use it in my controller and views.

**Comment by davemathews** [comment]
http://administrator.frozennode.com/docs/settings-configuration
@emocentmagar you have to use the before_save to store it in the database or a config that gets red into the app, however you want to use it at that point.
