### ISSUE TITLE
field for displaying json.

### ISSUE THREAD

**Issue by ziming** [FrozenNode/Laravel-Administrator#874]
Hi,

Currently I have a column in my table which stores json and I wonder if it would be a good idea to have a json field to display them nicely in an easy manner.

**Comment by davemathews** [comment]
json is nothing more than text and displays as such in the columns?  How would you want it displayed?

**Comment by ziming** [comment]
In a formatted way? And syntax coloured if it helps.

**Comment by davemathews** [comment]
@ziming thats going to take some third party helpers to do syntax coding.  but I will mark it as a future enhancement to look into.
