### ISSUE TITLE
Dashboard not showing

### ISSUE THREAD

**Issue by ziming** [FrozenNode/Laravel-Administrator#875]
Hi,

I enabled the dashboard option and in my view I had something like this

```
<h1>Dashboard Page!</h1>
```

In the rendered view html source I see something like this

```
<a href="http://localhost:8000" id="back_to_site">Back to Site</a>
			</div>
</header>
		<h1>Dashboard Page!</h1>
		<footer>
</footer>	</div>
```

However in the rendered view, all I see is the navigation bar at the top but the text "Dashboard Page!" did not appear.

**Comment by davemathews** [comment]
The dashboard view needs to have the div class to get the css to move it under the navigation like:
```html
<div class="table_container" style="margin-right: 290px;">
<h1>Dashboard Page!</h1>
</div>
```
