### ISSUE TITLE
Laravel 5: "The model option must be the string name of a valid Eloquent model"

### ISSUE THREAD

**Issue by sergiocastrovale** [FrozenNode/Laravel-Administrator#877]
What the title says. I have an User.php class under App/Models. Then the administrator.php under config/, and the settings folder and users.php in config/admin.

My paths are:

    'model_config_path' => config_path() . '/admin',
    'settings_config_path' => config_path() . '/admin/settings',
    'home_page' => 'users',

My users.php has this:

    return array(
      'title' => 'Users',
      'single' => 'user',
      'model' => 'User',

However when I try to access the home_page, I get the error:

There are problems with your users config: The model option must be the string name of a valid Eloquent model

I'm using my User model everywhere in the application, and if I die() while inside users.php that die() is called as it was supposed to. Any ideas?

**Comment by Geek-Daddy** [comment]
Change 'model' to 'App/Model/User'. Your model is in this namespace.

**Comment by sergiocastrovale** [comment]
Yes - silly me. Old code dies hard and I'm still finding my way around L5's namespace conventions. Thanks!

**Comment by KenPlayBalls** [comment]
hello,my User.php is under app, but when I change "model" to "app/User",it still went wrong, "There are problems with your user config: The model option must be the string name of a valid Eloquent model"
i have no idea how to work it out .....please save me   T.T

**Comment by DesmondPang** [comment]
It should be "App\ User" but not "app/User"
