### ISSUE TITLE
Failed calling App\Models\Enterprise::jsonSerialize()

### ISSUE THREAD

**Issue by ucc862** [FrozenNode/Laravel-Administrator#879]
When I use columns ,I got this Exception.
Next exception 'Exception' with message 'Failed calling App\Models\Enterprise::jsonSerialize()' in /var/www/ktv/vendor/frozennode/administrator/src/views/index.php:34

enterprise is a relationship use belongsTo .

public function enterprise()
    {
        return $this->belongsTo('App\Models\Enterprise', 'enterprise_id', 'enterprise_id');
    }
Here is the model config. I am using Laravel5.
'columns' => [
        'name' => [
            'title' => 'enterprise',
            'relationship' => 'enterprise',
            'select' =>  "(:table).name",
        ],
	],

**Comment by blonkm** [comment]
I have the exact same problem in Laravel 5

**Comment by davemathews** [comment]
this is an issue with the model relationship not returning a jsonable object, usually because there is an issue with one of the models.  The same whoops page will lead you to the error if you follow the tree of errors returned.

**Comment by ABDows** [comment]
I have the exact same problem in Laravel 5.1 when overriding _construct
