### ISSUE TITLE
Display multiple images using column relationship

### ISSUE THREAD

**Issue by kingdido999** [FrozenNode/Laravel-Administrator#880]
I'm a little confused about how to properly display multiple images in one column using model relationship. So I have two models: Product and ProductImage. A product has a hasMany method `images` that can retrieve product images. 

So in Product page, how do I display its product images in one column using `select` and `output` statements? Also, I've never seen a select statement like `(:table).id` before, is there any documentation on this?

**Comment by davemathews** [comment]
Its going to be hard to display multiple images in a single column from the relationship.  You may want to use a mutator to do all the work for you and then just use the output of that mutator to display in the admin column.  And here is the docs on the columns

http://administrator.frozennode.com/docs/model-configuration#columns
