### ISSUE TITLE
Build menu according to some conditions

### ISSUE THREAD

**Issue by sergiocastrovale** [FrozenNode/Laravel-Administrator#881]
I'm trying to build a menu with different options according to my $user->role. I was thinking about doing something like:

	'menu' => function() 
	{
                // Conditions here
		return [];
        },

but that doesn't work:

    There are problems with your administrator.php config: The menu option must be an array

 Can anyone help?

**Comment by davemathews** [comment]
since its based on your users role you can use the permission check closure in the administrator config and use the Config to set them.
```php
'permission'=> function() {
     if (Auth::check() && Auth::user()->role == 'whatever') {
        Config::push('administrator.menu', 'users');
    }
    return Auth::check();
}
```
