### ISSUE TITLE
404 Response for CSS, JS

### ISSUE THREAD

**Issue by larionov24e** [FrozenNode/Laravel-Administrator#889]
Guys, hi! Please help me somebody, i have a problem with response. I think it is depend with csrf. Help me please

![2015-07-01 22 08 12](https://cloud.githubusercontent.com/assets/6544899/8462668/fea4b5e4-203d-11e5-812c-6aeb47046148.png)

**Comment by jaumesala** [comment]
`artisan vendor:publish` maybe?

**Comment by larionov24e** [comment]
I did it .  i did not have packege files in root directory )

**Comment by larionov24e** [comment]
I did it .  i did not have packege files in root directory )
