### ISSUE TITLE
Change field type dynamically at edit_field section.

### ISSUE THREAD

**Issue by fernando1419** [FrozenNode/Laravel-Administrator#890]
Hi, I have a "settings" table containing these 3 fields:
1) key
2) value
3) type (1 = (used for images), 2 = (used for links) )

What I am trying to do is to get the correct field type according the value present in field Nº3 (type).
E.g. Let's say I have these 3 records:

a) 'twitter_logo', 'twitter.png', 1
b) 'twitter_url', 'https://twitter.com/xxxxxxx', 2
c) 'facebook_logo', 'facebook.png', 1

I need in edit_fields section, to get display the correct type of control at "value" field. So, it should display:
- An image control (type=image and the other properties) when editing record (a)
- An text control (type=text) when editing record (b)
- An image control (type=image and the other properties) when editing record (c)

Is there any way to accomplish this issue dynamically?.
Thanks in advance.
Fernando.

**Comment by davemathews** [comment]
there is no way to currently set the type dynamically for model configs.
