### ISSUE TITLE
HTML is rendered in text fields in item listings

### ISSUE THREAD

**Issue by judgej** [FrozenNode/Laravel-Administrator#891]
If a text field contains any HTML special characters (< > &) then if that text field is displayed as a column (i.e. in the item listings) then those HTML special characters are not escaped/encoded.

So a person named "Bobby \<strong\> Strong" will be displayed as:

> Bobby **Strong**

That's a bit dangerous. The listings should never display raw HTML straight from the database, expecting that data to display as simple strings and for there to be no formatting issues.

Is there a workaround for this, maybe an option to add to the columns to pass it through a filter like {{...}} does in blade?

**Comment by judgej** [comment]
Obviously whatever fixes this should not affect custom formatting such as in the "output" option, where you may well be adding your own HTML that you *do* want rendered as HTML.

**Comment by judgej** [comment]
A workaround is to do this on the `columns` entry:

~~~php
'output' => function($value) {return htmlentities($value, ENT_QUOTES, 'UTF-8', false);};
~~~

or if you have the HTML module installed:

~~~php
'output' => function($value) {return HTML::entities($value);};
~~~

**Comment by davemathews** [comment]
you have full control over your data with Administartor, and can use the output to manipulate it as needed.  that is not a workaround but is as intended to not box any one situation in, but give you the freedom to do as you see fit.

**Comment by judgej** [comment]
Flexibility is great, sure. It just seem crazy to me that *by default* including a field that could contain HTML tags (which is effectively *any* text field) in the listing, will be passed straight through to the browser without any kind of escaping or encoding. So developers need to manually override the rendering of every single text field to apply some protection.

I think that needs to be documented with a big warning, so people are aware of this.
