### ISSUE TITLE
Is there a set of registered route names to access pages in the admin area?

### ISSUE THREAD

**Issue by judgej** [FrozenNode/Laravel-Administrator#892]
So, I want to create a link to send the user to edit order number 3 with filter.

Then in another URL I need the link to send the user to the listing of order lines for order number 27, without editing any yet.

So where do I get these URLs from? Is there a helper function or class? Or are there any registered routes that will take me there (regardless of where "there" actually is, since the admin pages can moved around through the settings).

**Comment by judgej** [comment]
I guess I can set up some names routes myself, but I don't understand enough about the administration pages URL structure to do so. Is this documented somewhere that I'm just missing?

**Comment by judgej** [comment]
Ah, `src/routes.php`. This has all the routes that get registered, all with names that can be used. Looking in there, if I want to show the edit page for order number 3, then the URL will be:

    URL::route('admin_get_item', ['model' => 'orders', 'id' => 3])

That is the proper way to do it, so your application does not have to care how the data (model and ID) maps onto a URL.

-----------
Now, filters. Can they be set through the URL? Being able to land a user on a pre-filtered page makes absolute sense, and is pretty vital for managing structured data.

**Comment by davemathews** [comment]
@judgej you can do this through your auth so that if X user logs in you redirect him to the admin page you want to.  otherwise there is nothing baked into Administrator for Auth and redirecting based on it.  You could probably use route filters as well.

**Comment by judgej** [comment]
I'm not quite sure what you mean by that answer, because it doesn't seem to be answering a question I was asking.

**Comment by davemathews** [comment]
sorry @judgej look at query filters 
http://administrator.frozennode.com/docs/model-configuration#query-filter 
or if you wan t users to be able to take off the default filters you can do so setting the default values in the filters.
http://administrator.frozennode.com/docs/fields#filters
