### ISSUE TITLE
Bug using "Event" named model

### ISSUE THREAD

**Issue by csilvav** [FrozenNode/Laravel-Administrator#895]
I have a project where we use a named model as "Event" that extends from "Eloquent", so when I registered that model I was this "There are problems with your event config: The model option must be the string name of a valid Eloquent model". 

However checking all files, relationships, names, fields, etc.. everything was Ok. so I tested and did some changes to may solve or find a workaround for that problem, and the real problem is the "name" for model, don't know if the issue is because the laravel project has another named "Event" classes.

Screenshot where is fired the exception.

![snap 2015-07-13 at 18 08 48](https://cloud.githubusercontent.com/assets/8739786/8662896/3afce2dc-298a-11e5-9255-ba50896a93e1.png)

**Comment by davemathews** [comment]
Can you post your model and config?

**Comment by davemathews** [comment]
Also name spacing would fix this issue.
