### ISSUE TITLE
Strange behavior in "Items per Page"

### ISSUE THREAD

**Issue by csilvav** [FrozenNode/Laravel-Administrator#897]
The element "Items per Page" has a error when I'm going to change value for it.

This is when everything is ok, at start admin module.

![image](https://cloud.githubusercontent.com/assets/8739786/8663068/2f71fffe-298c-11e5-8f9b-5b13b4d57a85.png)

This is when I changed the value from 12 items to 20 items or another.

![image](https://cloud.githubusercontent.com/assets/8739786/8663083/74eb0e9a-298c-11e5-9136-4a0b0c47ad3c.png)

**Comment by ccodina** [comment]
same problem for me with chrome Version 43.0.2357.134 (64-bit) on ubuntu.
it works with firefox...

**Comment by Geroy12** [comment]
I just remove "overflow:hidden" fot this element.

**Comment by Vishnja** [comment]
Yes, removing "overflow:hidden" helps.

 main.css:1182

#admin_page #content div.table_container div.page_container div.per_page {
...
overflow: hidden;
}

**Comment by ccodina** [comment]
thx for the answers

best regards,
chris

**Comment by davemathews** [comment]
duplicate #915 so closing please follow that one for updates
