### ISSUE TITLE
cannot login my administrator twice

### ISSUE THREAD

**Issue by KenPlayBalls** [FrozenNode/Laravel-Administrator#898]
hi,nice guys!
At the first time when i try to login my adminstrator,it works.
However,when i try to login the second time,it fails.
The warning is 'NotFoundHttpException'
AND my postLogin in my AuthController is like this:
 $email = Input::get('email');
        $password = Input::get('password');

        if (Auth::attempt(['email' => $email, 'password' => $password]))
        {
            return Redirect::intended('/admin');
        }

        return Redirect::back()
            ->withInput()
            ->withErrors('Email or Password are incorrect.');

Could someone give me a hand?It has driven me mad!!!!
THANKS!

**Comment by davemathews** [comment]
try taking out the slash:
```php
if (Auth::attempt(['email' => $email, 'password' => $password]))
    {
        return Redirect::intended('admin');
    }
```
