### ISSUE TITLE
Field Type - Image: Prefix Path to Image Name

### ISSUE THREAD

**Issue by arcarim** [FrozenNode/Laravel-Administrator#900]
# Add Prefix To Image Name

I am saving images with the 'random' option to my database. Hence the random name will get posted as per the first entry on the image below . However, what I'd prefer to do was to save the random image name with a prefix to the image column in my database, e.g.  *IFUvCMdWtQyEOtmFp2zX.jpg*  => *pics/products/IFUvCMdWtQyEOtmFp2zX.jpg*
Is there a way to achieve this with the current features or do I have to hard code that to the source files? 

![screenshot from 2015-07-18 20 34 53](https://cloud.githubusercontent.com/assets/13396580/8763054/7c54893c-2d8c-11e5-983a-2bb1353c3f3a.png)

**Comment by davemathews** [comment]
this is not possible currently
