### ISSUE TITLE
XSS Injection problem 

### ISSUE THREAD

**Issue by MaxKosenko** [FrozenNode/Laravel-Administrator#903]
Please add quote string with slashes and protection against XSS attacks.
You can reproduce that critical issue but storing in the edit form simple XSS:
<script type="text/javascript">alert('hello devs')</script>

**Comment by MaxKosenko** [comment]
We've got some escaped code from ours WP Devs in the DB and it ruin JS scripts:
<SCRIPT TYPE=\"TEXT/JAVASCRIPT\">ALERT(\"HELLO\")</SCRIPT>
![admin_issue](https://cloud.githubusercontent.com/assets/1991722/8905821/2419e54a-3472-11e5-9f19-5d9389f1c606.png)

**Comment by davemathews** [comment]
you can protect it by using a mutator within your model. not sure we are going to do this right now.

**Comment by feridmovsumov** [comment]
I am agree with @MaxKosenko there is xss vulnerability here.
