### ISSUE TITLE
Underfined variable: redirectKey

### ISSUE THREAD

**Issue by magamlag** [FrozenNode/Laravel-Administrator#914]
I'm getting exception if add Redirect with custom error message to Closure of permissions:
```
'permission'=> function()
	{
        $user = Auth::user();
        if($user->hasRole('admin'))
            return true;
        elseif($user)
            return Redirect::to('home/dashboard')->withError('You do not have permission to access this resource');
        else
            return Redirect::guest('home/login');
    },
```
Reason of this exception:
```
$redirectKey = Config::get('administrator::administrator.login_redirect_key', 'redirect');
    $redirectUri = Request::url();
```
In file filter.php this part of code(line: 18,19) need to move before if statement
In case if use package - FrozenNode for Laravel 4

**Comment by davemathews** [comment]
permission expects to return a bool true or false, not a Redirect, we use the login_redirect_key so you can set the key in the session and return false to get this the way you want it.

http://administrator.frozennode.com/docs/configuration#redirect-key
