### ISSUE TITLE
Error displaying items in the frontend when pagination

### ISSUE THREAD

**Issue by scriptixru** [FrozenNode/Laravel-Administrator#915]
![screenshot_3](https://cloud.githubusercontent.com/assets/11806645/9515699/90b23bb6-4cab-11e5-8944-e443a9a7a05a.jpg)
1. When you change the display of the number of elements on the page, the box with the numbers disappear. This happens in the Opera browser, Chrome. In Mozilla Firefox everything is fine.

![screenshot_1](https://cloud.githubusercontent.com/assets/11806645/9515812/a2321c66-4cac-11e5-94dc-24297cc0bb2f.jpg)
2. When it comes the number of elements on the page, pagination. By clicking on the "next" and "prev"  button,  nothing happens. No updates to display the desired number of items. 
It seems that JavaScript does not fulfill, but when saved after editing the item, then pagination work.

**Comment by scriptixru** [comment]
2. When it comes the number of elements on the page, pagination.
I noticed that on other pages work exactly on this - no.
It does not work because this block is described in the config file:
        'page'=>[
              'title'=>'На главной или др. странице',
              'type' => 'relationship',
              'name_field' => 'rustitlepage',
              'relationship' => 'page',
         ],

It turns out she is very sensitive about the word "page", had to change the model name "Page" and it worked.

**Comment by davemathews** [comment]
will mark as bug and have to test this out, thanks.

**Comment by davemathews** [comment]
follow #848 for updates when this is fixed.
@scriptixru you dont need the relationship defined and the type relationship in that stanza.
