### ISSUE TITLE
Laravel 5.1 

### ISSUE THREAD

**Issue by microdesign** [FrozenNode/Laravel-Administrator#916]
Is this plugin compability with Laravel 5.1 at all?
Because I always get 'There are problems with your posts config: The model option must be the string name of a valid Eloquent model'

**Comment by janhartigan** [comment]
I use it with 5.1 every day. Chances are the model string you've provided doesn't extend from the base eloquent model or doesn't exist.

**Comment by bradis** [comment]
Hello please with laravel 5.1 you can make a simple custom page sample because always I got this error Administrator: You must provide a valid menu item in the home_page option of your config

**Comment by bradis** [comment]
Any way to change the default template without modifying the contents of the folder vendor?

Thanks

**Comment by BenWoodford** [comment]
Make sure you use the full namespaced 'path' to your model. Usually just App\User or similar if you're working off the defaults.

**Comment by davemathews** [comment]
@microdesign @janhartigan and @BenWoodford are correct here, your referencing your model incorrectly in the administrator model config.

@bradis please see the docs at: http://administrator.frozennode.com/docs/configuration#home-page
