### ISSUE TITLE
Session not working for downloading files on AdminController.php

### ISSUE THREAD

**Issue by lombardicz** [FrozenNode/Laravel-Administrator#917]
Hello, 

I think there is an issue with the session on this file.  

You use for saving the filename in the session this:

$this->session->put('administrator_download_response', array('file' => $file, 'headers' => $headers));

But you have declared session as a Laravel 5 class, so you should use this syntax:

$this->session(['administrator_download_response' => array('file' => $file, 'headers' => $headers)]); 

It wasn't working for me until I:
- Replaced "use Illuminate\Session\SessionManager as Session" for "use Session" 
- Removed "Session $session" from the constructor 
- Replaced all "$this->session->put" with "Session::put"

Hope this helps,

Diego Lombard

**Comment by davemathews** [comment]
fixed in v5.0.5
