### ISSUE TITLE
Default Authorizarion for role and permission

### ISSUE THREAD

**Issue by nasirkhan** [FrozenNode/Laravel-Administrator#920]
are you using the Laravel Authorizarion for role and permission? when will we get this?

**Comment by davemathews** [comment]
This is not currently in the codebase, but we are looking at an Administrator 5.1 release that will take advantage of that.

**Comment by nasirkhan** [comment]
@davemathews, thanks. can you please share the expected release date?

**Comment by davemathews** [comment]
@nasirkhan we were just talking about it today, so no planned release date for it, as we are just in the early stages but as soon as possible we will.
