### ISSUE TITLE
Help me, blank page

### ISSUE THREAD

**Issue by vad11** [FrozenNode/Laravel-Administrator#921]
I see blank page, but code of page 

localhost:8000/admin/users

<div id="admin_page" class="with_sidebar">
	<div id="sidebar">
		<div class="panel sidebar_section" id="filters_sidebar_section" data-bind="template: 'filtersTemplate'"></div>
	</div>
	<div id="content" data-bind="template: 'adminTemplate'"></div>
</div>

<script type="text/javascript">
	var site_url = "http://localhost:8000",
		base_url = "http://localhost:8000/admin/",
		asset_url = "http://localhost:8000/packages/frozennode/administrator",
		file_url = "http://localhost:8000/admin/users/file",
		rows_per_page_url = "http://localhost:8000/admin/users/rows_per_page",
		route = "/admin/",
		csrf = "5YIIKL49zkqGRm89UC4QoWNgWj5yAadLj2BuylKf",
		language = "en",
		adminData = {
			primary_key: "id",
						rows: {"page":1,"last":1,"total":1,"results":[{"id":{"raw":1,"rendered":"1"},"name":{"raw":"vadim","rendered":"vadim"},"email":{"raw":"vadim@vadim.com","rendered":"vadim@vadim.com"}}]},
			rows_per_page: 20,
			sortOptions: {"field":"id","direction":"desc"},
			model_name: "users",
			model_title: "Users",
			model_single: "user",
			expand_width: 285,
			actions: [],
			global_actions: [],
			filters: [],
			edit_fields: {"email":{"relationship":false,"external":false,"editable":true,"visible":true,"setter":false,"description":"","value":"","min_value":"","max_value":"","min_max":false,"limit":0,"height":100,"type":"text","field_name":"email","title":"email"},"id":{"relationship":false,"external":false,"editable":false,"visible":false,"setter":false,"description":"","value":"","min_value":"","max_value":"","min_max":false,"field_name":"id","title":"id","type":"key"}},
			data_model: {"email":"","id":0},
			column_model: [{"relationship":false,"sortable":true,"select":false,"output":"(:value)","sort_field":"id","nested":[],"is_related":false,"is_computed":false,"is_included":true,"external":false,"belongs_to_many":false,"visible":true,"column_name":"id","title":"id"},{"relationship":false,"sortable":true,"select":false,"output":"(:value)","sort_field":"name","nested":[],"is_related":false,"is_computed":false,"is_included":true,"external":false,"belongs_to_many":false,"visible":true,"column_name":"name","title":"name"},{"relationship":false,"sortable":true,"select":false,"output":"(:value)","sort_field":"email","nested":[],"is_related":false,"is_computed":false,"is_included":true,"external":false,"belongs_to_many":false,"visible":true,"column_name":"email","title":"email"}],
			action_permissions: {"create":true,"delete":true,"update":true,"view":true},
			languages: {"delete_active_item":"Are you sure you want to delete this item? This cannot be reversed.","saving":"Saving...","saved":"Item saved.","deleting":"Deleting...","deleted":"Item deleted.","character_left":" character left","characters_left":" characters left","no_results":"No results matched","select_options":"Select Some Options"}		};
</script>

<style type="text/css">

	div.item_edit form.edit_form select, div.item_edit form.edit_form input[type=hidden], div.item_edit form.edit_form .select2-container {
		width: 226px !important;
	}

	div.item_edit form.edit_form .cke {
		width: 218px !important;
	}

	div.item_edit form.edit_form div.markdown textarea {
		width: 93px !important;
		max-width: 93px !important;
	}

	div.item_edit form.edit_form div.markdown div.preview {
		width: 105px !important;
	}

	div.item_edit form.edit_form input[type="text"], div.item_edit form.edit_form input[type="password"], div.item_edit form.edit_form textarea {
		max-width: 210px !important;
		width: 210px !important;
	}

	div.item_edit form.edit_form > div.image img, div.item_edit form.edit_form > div.image div.image_container {
		max-width: 220px;
	}

</style>

<input type="hidden" name="_token" value="5YIIKL49zkqGRm89UC4QoWNgWj5yAadLj2BuylKf" />

<script id="adminTemplate" type="text/html">
	<div class="table_container">

	<div class="results_header">
		<h2 data-bind="text: modelTitle"></h2>

		<div class="actions">
			
				
					
						<input type="button" data-bind="click: function(){$root.customAction(false, action_name, messages, confirmation)}, value: title,
																		attr: {disabled: $root.freezeForm() || $root.freezeActions()}" />
					
				
			
			
				<a class="new_item"
					data-bind="attr: {href: base_url + modelName() + '/new'},
								text: 'New ' + modelSingle()"></a>
			
		</div>

		<div class="action_message" data-bind="css: { error: globalStatusMessageType() == 'error', success: globalStatusMessageType() == 'success' },
										notification: globalStatusMessage "></div>
	</div>

	<div class="page_container">
		<div class="per_page">
			<input type="hidden" data-bind="value: rowsPerPage, select2: {minimumResultsForSearch: -1, data: {results: rowsPerPageOptions},
											allowClear: false}" />
			<span> items per page</span>
		</div>
		<div class="paginator">
			<input type="button" value="prev"
					data-bind="attr: {disabled: pagination.isFirst() || !pagination.last() || !initialized() }, click: function() {page('prev')}" />
			<input type="button" value="next"
					data-bind="attr: {disabled: pagination.isLast() || !pagination.last() || !initialized() }, click: function() {page('next')}" />
			<input type="text" data-bind="attr: {disabled: pagination.last() === 0 || !initialized() }, value: pagination.page" />
			<span data-bind="text: ' / ' + pagination.last()"></span>
		</div>
	</div>

	<table class="results" border="0" cellspacing="0" id="customers" cellpadding="0">
		<thead>
			<tr>
				
					<th data-bind="visible: visible, css: {sortable: sortable,
	'sorted-asc': (column_name == $root.sortOptions.field() || sort_field == $root.sortOptions.field()) && $root.sortOptions.direction() === 'asc',
	'sorted-desc': (column_name == $root.sortOptions.field() || sort_field == $root.sortOptions.field()) && $root.sortOptions.direction() === 'desc'}">
						
							<div data-bind="click: function() {$root.setSortOptions(sort_field ? sort_field : column_name)}, text: title"></div>
						

						
							<div data-bind="text: title"></div>
						
					</th>
				
			</tr>
		</thead>
		<tbody>
			
				<tr data-bind="click: function() {$root.clickItem($data[$root.primaryKey].raw); return true},
							css: {result: true, even: $index() % 2 == 1, odd: $index() % 2 != 1,
									selected: $data[$root.primaryKey].raw == $root.itemLoadingId()}">
					
						<td data-bind="html: $parentContext.$data[column_name].rendered, visible: visible"></td>
					
				</tr>
			
		</tbody>
	</table>

	<div class="loading_rows" data-bind="visible: loadingRows">
		<div>Loading...</div>
	</div>

	<div class="no_results" data-bind="visible: pagination.last() === 0">
		<div>No Results</div>
	</div>
</div>

<div class="item_edit_container" data-bind="itemTransition: activeItem() !== null || loadingItem(), style: {width: expandWidth() + 'px'}">
	<div class="item_edit" data-bind="template: 'itemFormTemplate', style: {width: (expandWidth() - 27) + 'px'}"></div>
</div></script>

<script id="itemFormTemplate" type="text/html">
	<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>
            /* Copyright (c) 2010, Yahoo! Inc. All rights reserved. Code licensed under the BSD License: http://developer.yahoo.com/yui/license.html */
            html{color:#000;background:#FFF;}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0;}table{border-collapse:collapse;border-spacing:0;}fieldset,img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}li{list-style:none;}caption,th{text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;}q:before,q:after{content:'';}abbr,acronym{border:0;font-variant:normal;}sup{vertical-align:text-top;}sub{vertical-align:text-bottom;}input,textarea,select{font-family:inherit;font-size:inherit;font-weight:inherit;}input,textarea,select{*font-size:100%;}legend{color:#000;}

            html { background: #eee; padding: 10px }
            img { border: 0; }
            #sf-resetcontent { width:970px; margin:0 auto; }
                        .sf-reset { font: 11px Verdana, Arial, sans-serif; color: #333 }
            .sf-reset .clear { clear:both; height:0; font-size:0; line-height:0; }
            .sf-reset .clear_fix:after { display:block; height:0; clear:both; visibility:hidden; }
            .sf-reset .clear_fix { display:inline-block; }
            .sf-reset * html .clear_fix { height:1%; }
            .sf-reset .clear_fix { display:block; }
            .sf-reset, .sf-reset .block { margin: auto }
            .sf-reset abbr { border-bottom: 1px dotted #000; cursor: help; }
            .sf-reset p { font-size:14px; line-height:20px; color:#868686; padding-bottom:20px }
            .sf-reset strong { font-weight:bold; }
            .sf-reset a { color:#6c6159; cursor: default; }
            .sf-reset a img { border:none; }
            .sf-reset a:hover { text-decoration:underline; }
            .sf-reset em { font-style:italic; }
            .sf-reset h1, .sf-reset h2 { font: 20px Georgia, "Times New Roman", Times, serif }
            .sf-reset .exception_counter { background-color: #fff; color: #333; padding: 6px; float: left; margin-right: 10px; float: left; display: block; }
            .sf-reset .exception_title { margin-left: 3em; margin-bottom: 0.7em; display: block; }
            .sf-reset .exception_message { margin-left: 3em; display: block; }
            .sf-reset .traces li { font-size:12px; padding: 2px 4px; list-style-type:decimal; margin-left:20px; }
            .sf-reset .block { background-color:#FFFFFF; padding:10px 28px; margin-bottom:20px;
                -webkit-border-bottom-right-radius: 16px;
                -webkit-border-bottom-left-radius: 16px;
                -moz-border-radius-bottomright: 16px;
                -moz-border-radius-bottomleft: 16px;
                border-bottom-right-radius: 16px;
                border-bottom-left-radius: 16px;
                border-bottom:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
            }
            .sf-reset .block_exception { background-color:#ddd; color: #333; padding:20px;
                -webkit-border-top-left-radius: 16px;
                -webkit-border-top-right-radius: 16px;
                -moz-border-radius-topleft: 16px;
                -moz-border-radius-topright: 16px;
                border-top-left-radius: 16px;
                border-top-right-radius: 16px;
                border-top:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
                overflow: hidden;
                word-wrap: break-word;
            }
            .sf-reset a { background:none; color:#868686; text-decoration:none; }
            .sf-reset a:hover { background:none; color:#313131; text-decoration:underline; }
            .sf-reset ol { padding: 10px 0; }
            .sf-reset h1 { background-color:#FFFFFF; padding: 15px 28px; margin-bottom: 20px;
                -webkit-border-radius: 10px;
                -moz-border-radius: 10px;
                border-radius: 10px;
                border: 1px solid #ccc;
            }
        </style>
    </head>
    <body>
                    <div id="sf-resetcontent" class="sf-reset">
                <h1>Whoops, looks like something went wrong.</h1>
                                        <h2 class="block_exception clear_fix">
                            <span class="exception_counter">1/1</span>
                            <span class="exception_title"><abbr title="Symfony\Component\Debug\Exception\FatalErrorException">FatalErrorException</abbr> in <a title="D:\xampp_ganim\htdocs\www\laravel5\test_admin\vendor\frozennode\administrator\src\views\index.php line 0" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">index.php line 0</a>:</span>
                            <span class="exception_message">Method Illuminate\View\View::__toString() must not throw an exception</span>
                        </h2>
                        <div class="block">
                            <ol class="traces list_exception">       <li> in <a title="D:\xampp_ganim\htdocs\www\laravel5\test_admin\vendor\frozennode\administrator\src\views\index.php line 0" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">index.php line 0</a></li>
    </ol>
</div>

            </div>
    </body>
</html>

**Comment by davemathews** [comment]
@vad11 we need more information with issues like these.  looks as if your setup is wrong. Get me more info and open another ticket please.
