### ISSUE TITLE
Not show page in laravel 5.1. In laravel 5.0 work ok

### ISSUE THREAD

**Issue by vad11** [FrozenNode/Laravel-Administrator#922]
Not show page in laravel 5.1. In laravel 5.0 work ok

**Comment by davemathews** [comment]
@vad11 it is tested and works in 5.1 you will need to give me more details for help.

**Comment by vad11** [comment]
I try laravel 5.0 and 5.1. 5.1 not show admin page (page contain code, but not show).
5.0 work exellent.
