### ISSUE TITLE
Problem in Laravel 5.1

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [FrozenNode/Laravel-Administrator#923]
InvalidArgumentException in Config.php line 79:
There are problems with your topics config: The model option must be the string name of a valid Eloquent model

cat config/administrator/topics.php

<?php
return array(
'title' => 'Topics',
'single' => 'topic',
'model' => 'App/Topic',
'columns' => array(
    'name' => array(
        'title' => 'Name'
    )
),
'edit_fields' => array(
    'name' => array(
        'title' => 'Name',
        'type' => 'text'
    )
)
);

cat app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    public functions books()
    {
        return $this->has_many_and_belongs_to('Topic','books_topics');
    }

}

**Comment by almahozi** [comment]
I think what you need is `'model' => 'App/Topic',`

**Comment by davemathews** [comment]
@almahozi is right @andersondeoliveiramachado you have your model definition wrong here.
