### ISSUE TITLE
Dynamic Image Location

### ISSUE THREAD

**Issue by almahozi** [FrozenNode/Laravel-Administrator#924]
I have a case where the image location depends on the id of the model in hand. So in the image location I can't provide just a string. I need something like this.

````php
'edit_fields'  => [
      'profile'	=>	[
			'title'	=>	'Profile Image',
			'type'	=>	'image',
			'location'	=>	public_path() . '/images/products/[product_id]/'
		]
]
````

I have tried using a closure with the model as an aurgument but it didn't work.
````php
'location' => function($model) { return public_path() . '/images/products/' . $model->id; }
````
I also tried using an accessor but it gave an error saying that location must be a valid directory.

Is there anyway to make this work?

**Comment by davemathews** [comment]
No this is not currently possible, you can't access the model this way
