### ISSUE TITLE
Create related fields "on fly"

### ISSUE THREAD

**Issue by Vishnja** [FrozenNode/Laravel-Administrator#932]
Hello! What is possible workaround to create related field "on fly"? By that I mean a possibilty to create and edit multiple records from child table while editing parent. 
E.g. Individual gallery on each page. Each slide of gallery can have title and image. So while editing page in admin, I can click on relationship field and then in POP UP for example I can load image and edit title. After saving it's automatically added to relationship select and it's possible to change order of items (either by dragging or some other method) and delete items.

**Comment by davemathews** [comment]
the ability is not really out of the box
