### ISSUE TITLE
Adding custom placeholder text on inputs

### ISSUE THREAD

**Issue by sergiocastrovale** [FrozenNode/Laravel-Administrator#933]
Is there any way I can add custom placeholder texts on specific inputs of a form?

**Comment by davemathews** [comment]
you can either do it as a default "value" set on the field or with some custom css and js

**Comment by sergiocastrovale** [comment]
A default value is not really a solution because it gets saved. A placeholder does not. Couldn't this be added as an optional parameter in the array?
