### ISSUE TITLE
how can i use in 5.1

### ISSUE THREAD

**Issue by cnzhangxl** [FrozenNode/Laravel-Administrator#936]
how can i use in 5.1

**Comment by niahoo** [comment]
Same as before. Are you experiencing any trouble ?

**Comment by cnzhangxl** [comment]
in 5.1
error:
InvalidArgumentException in Factory.php line 104: There are problems with your administrator.php config: The model config path option must be a valid directory. The settings config path option must be a valid directory. The menu field is required.


administrator.php
	/**
	 * The path to your model config directory
	 *
	 * @type string
	 */
	'model_config_path' => config_path('administrator'),

	/**
	 * The path to your settings config directory
	 *
	 * @type string
	 */
	'settings_config_path' => config_path('administrator/settings'),

**Comment by niahoo** [comment]
So, the errors are well explained. Start by resolving these three issues (create the directories and add the 'menu' entry in your administrator.php config).

**Comment by cnzhangxl** [comment]
php artisan asset:publish frozennode/administrator

  [InvalidArgumentException]                               
  There are no commands defined in the "asset" namespace.

**Comment by cnzhangxl** [comment]
where the controller and view file???

**Comment by niahoo** [comment]
In 5.1 you just fire `php artisan vendor:publish`

**Comment by niahoo** [comment]
THe config file should appear. You may have to create the directory `config/administrator/settings` by hand.

**Comment by davemathews** [comment]
@niahoo is correct on this, we will update the docs for 5.1

**Comment by king724** [comment]
I am also trying to use this on 5.1.  

I run `php artisan vendor:publish` as mentioned above but i receive `Nothing to publish for tag [].`

**Comment by niahoo** [comment]
are you sure laravel-administrator is installed ?

**Comment by ricoa** [comment]
I have the same trouble when I run php artisan vendor:publish

**Comment by alex621** [comment]
Better make the documentation structure clearer. I thought that we still need to publish asset in 5.1 when I read the documentation.
