### ISSUE TITLE
Unable to change the text value of a relationship dropdown

### ISSUE THREAD

**Issue by sergiocastrovale** [FrozenNode/Laravel-Administrator#938]
I have a three level structure like Category » Subcategory » Product.

I'm trying to make it so that when I create or edit a product, my subcategory relationship shows something like:

* Category1 » Subcategory1
* Category1 » Subcategory2

Currently I'm trying to override the query of products.php in this way:

```php
    'subcategory' => [
        'title' => 'Category tree',
        'type' => 'relationship',
        'name_field' => 'tree',
        'options_filter' => function($query) {

            $str = 'select CONCAT(cat.name, " » ", sc.name) as tree, 
            cat.id, cat.name, sc.id, sc.name
                    from categories cat
                    inner join subcategories sc on sc.category_id = cat.id';

            $query = \DB::table('subsubcategories')->select(\DB::raw($str));

            return $query;
        }
    ],
```
However this outputs a blank result set in Administrator's dropdown, I'm guessing because 'tree' doesn't really exist as a valid name_field. Is there any way of handling this?

Any help would be greatly appreciated.

**Comment by davemathews** [comment]
I would put a getter attribute on the subcategory model that returns the correct "Category1 » Subcategory1" for the model and then use that as the name_field and you would not have to do any of the options_filter you are doing.

**Comment by sergiocastrovale** [comment]
@davemathews  Can you provide a mockup example of such getter? I'm not sure I'm following. Isn't the name_field just retrieving a column value? Thanks!

**Comment by davemathews** [comment]
@sergiocastrovale show me what your model looks like for category, product and subcategory and I will give you an example.  Here is getter docs from laravel:  http://laravel.com/docs/master/eloquent-mutators#accessors-and-mutators

**Comment by sergiocastrovale** [comment]
@davemathews Nevermind, I found out how to do it, I wasn't getting the right picture. Here's the solution for the whole tree in case someone needs it.

In my Subcategory.php:

```php
	public function getNameWithTreeAttribute($value)
	{
		$localized_name = 'name_' . getCurrentLocale();

		return $this->subcategory[$localized_name] . ' » ' . $this[$localized_name];
	}
```
