### ISSUE TITLE
Sorry, the page you are looking for could not be found.

### ISSUE THREAD

**Issue by jinjiang2009** [FrozenNode/Laravel-Administrator#949]
i use laravel5.1.4. the problem is "Sorry, the page you are looking for could not be found.".

can someone help me?thankyou

**Comment by davemathews** [comment]
sounds like you are not installed correctly cause the routes are not picking up. Please follow these instructions:
https://github.com/FrozenNode/Laravel-Administrator/blob/dev/docs/installation.md
