### ISSUE TITLE
Can't do vendor:publish

### ISSUE THREAD

**Issue by olszak94** [FrozenNode/Laravel-Administrator#951]
Whenever i do `php artisan vendor:publish` it's publishing but only other packages, not tis one. There's no errors.

**Comment by davemathews** [comment]
sounds like the installation is bad???  try doing it only for the Administrator

```php
php artisan vendor:publish --provider='Frozennode\Administrator\AdministratorServiceProvider'
```

**Comment by olszak94** [comment]
Fixed it by adding composer require manually to json file and then
updating. Although I have some problems with settings path. Will post error
in few minutes

W dniu pt., 13 lis 2015 o 15:19 David Mathews <notifications@github.com>
napisał(a):

**Comment by davemathews** [comment]
http://administrator.frozennode.com/docs/configuration
