### ISSUE TITLE
Link to related Object

### ISSUE THREAD

**Issue by aktiWeb** [FrozenNode/Laravel-Administrator#955]
Hi,

how can i place a Link into every Table Row to a related Object?
In the "Comments" Table i would like to have Links "Open Post" to open the related Post.

Is this possible?

Many Thanks
Dietmar

**Comment by davemathews** [comment]
yes using the following docs. http://administrator.frozennode.com/docs/columns#custom-outputs  the model is available in the closure as $model now as well.
```php
'hex' => array(
    'title' => 'Color',
    'output' => function($value, $model)
    {
        return '<a href="/admin/(model_name_here)/'.$model->id.'">(:value)</a>';
    },
),
```
