### ISSUE TITLE
Relationship Field Filter

### ISSUE THREAD

**Issue by codydh** [FrozenNode/Laravel-Administrator#958]
I might be missing something, but right now it looks like if I've got a column displayed as such:

```'revisionable_id' => array('title' => 'NetID', 'relationship' => 'researcher', 'select' => "(:table).netid"),```

That there's no way to create a filter based on the display value of that column (e.g., 'userid') versus the actual value (e.g., '128'). Is this the case?

**Comment by davemathews** [comment]
you could using a text field filter for that column, but not with a relationship column in the filter for it.
