### ISSUE TITLE
Auth::check() not works at config file use laravel 5.2

### ISSUE THREAD

**Issue by dhlwing** [FrozenNode/Laravel-Administrator#965]
```php
'permission'=> function()
    {
        // return true;
        return Auth::check();
    },
```
even i'm login, this code still return a false.

**Comment by davemathews** [comment]
get the latest version of Administrator 5.0.11 that uses the new middleware config option.  Since L5.2 uses the web route middleware for its scaffolded auth add it to the middleware config in the administrator file and you will find it working again.

**Comment by dhlwing** [comment]
@davemathews thx very much,i'll try it later
