### ISSUE TITLE
Eloquent query inside administrator config or model config files ?

### ISSUE THREAD

**Issue by ElSifi** [FrozenNode/Laravel-Administrator#970]
I need the menu items to be dynamic, is possible to perform an eloquent query inside administrator config or model config files ?

I tried by using Elequent and DB but doesn't work.
    
    Fatal error: Call to a member function table() on null in /home/vagrant/Code/project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line

**Comment by namreg** [comment]
@ElSifi Provide your code example, please

**Comment by ElSifi** [comment]
Like this

in the Administrator.php config file

    <?php
    return array(
    	'uri' => 'manage',
    	'title' => \App\Setting::find(5)->value,
    	'model_config_path' => config_path('administrator'),
    	'settings_config_path' => config_path('administrator/settings'),

I get this error
    Fatal error: Call to a member function connection() on null in /home/vagrant/Code/projectFolder/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 3146

**Comment by namreg** [comment]
@ElSifi I think that config file is not a place for querying the db. Do the job in a service provider for example. In service provider you can do something like that:
```php
config(['administrator.title' => \App\Setting::find(5)->value]);
```
This should work.

**Comment by ElSifi** [comment]
Great.
Thank Igor.
