### ISSUE TITLE
Redirected to root page

### ISSUE THREAD

**Issue by surgiie** [FrozenNode/Laravel-Administrator#994]
Hi i just installed Laravel Administrator on L5 and configured the files i have an auth check to redirect users to auth/login if they are not logged in but once they login im simply redirected to /

Currently im only testing one model at a time so i have a the menu array with one model student 
'menu' => array(

'student'

),

and the home_page field set to student...
'home_page' => 'student',

i also have a student model config file and have the paths configured right...not sure why im simply redirected to home page?:(

**Comment by surgiie** [comment]
Nevermind i found a solution according to issue #969 

Thanks to @patrickcarlohickman:

I don't use this package, but I investigated the issue for this question on SO: http://stackoverflow.com/questions/34856389/laravel-frozennode-authcheck-always-return-false

Basically, the issue is that the FrozenNode routes are not inside the web middleware group. Because of this, the session is not available, and therefore Auth::check() will always be false.

All you need to do is add web to the middleware key in your administrator.php configuration.

return array(
    // ...
    'middleware' => array('web'),
    // ...
);

**Comment by jonahkoo** [comment]
very helpful

**Comment by surgiie** [comment]
@jonahkoo  im glad it was useful to you!
